/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * DADOS REAIS DO 1º SIMULADO MUNICIPAL DE FLUÊNCIA LEITORA 2026 (PARTE 1)
 * Matriz consolidada por Unidade Escolar e Turma (24 escolas avaliadas)
 */

export interface Simulado1ClassData {
  id: string;
  escola: string;
  turma: string;
  prev?: number;
  avaliados: number;
  participacao?: number;
  n1Count: number;
  n2Count: number;
  n3Count: number;
  n4Count: number;
  inicianteCount: number;
  fluenteCount: number;
  n1Perc: number;
  n2Perc: number;
  n3Perc: number;
  n4Perc: number;
  iniciantePerc: number;
  fluentePerc: number;
  preTotalPerc: number;
  leitoresPerc: number;
  iflNum: number;
  ifl: string;
  isPendente?: boolean;
  statusNota?: string;
}

export interface Simulado1SchoolData {
  name: string;
  rawName: string;
  iflGeral: number;
  iflGeralFormatted: string;
  classes: Simulado1ClassData[];
  isPendingBatch?: boolean;
}

/**
 * 37 Escolas da Rede Municipal - 1º Simulado 2026 (100% Auditadas e Consolidadas)
 */
export const SIMULADO1_SCHOOLS_RAW: Simulado1SchoolData[] = [
  {
    name: "E.M. PROFª ISABEL DO CARMO NOGUEIRA",
    rawName: "E.M. PROFª ISABEL DO CARMO NOGUEIRA",
    iflGeral: 7.03,
    iflGeralFormatted: "7.03",
    classes: [
      {
        id: "E.M. PROFª ISABEL DO CARMO NOGUEIRA__2º Ano A",
        escola: "E.M. PROFª ISABEL DO CARMO NOGUEIRA",
        turma: "2º Ano A",
        avaliados: 23,
        n1Count: 1,
        n2Count: 1,
        n3Count: 4,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 9,
        n1Perc: 4.3,
        n2Perc: 4.3,
        n3Perc: 17.4,
        n4Perc: 0.0,
        iniciantePerc: 34.8,
        fluentePerc: 39.1,
        preTotalPerc: 26.1,
        leitoresPerc: 73.9,
        iflNum: 6.83,
        ifl: "6.83"
      },
      {
        id: "E.M. PROFª ISABEL DO CARMO NOGUEIRA__2º Ano B",
        escola: "E.M. PROFª ISABEL DO CARMO NOGUEIRA",
        turma: "2º Ano B",
        avaliados: 22,
        n1Count: 0,
        n2Count: 0,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 17,
        fluenteCount: 3,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 9.1,
        n4Perc: 0.0,
        iniciantePerc: 77.3,
        fluentePerc: 13.6,
        preTotalPerc: 9.1,
        leitoresPerc: 90.9,
        iflNum: 6.23,
        ifl: "6.23"
      },
      {
        id: "E.M. PROFª ISABEL DO CARMO NOGUEIRA__2º Ano C",
        escola: "E.M. PROFª ISABEL DO CARMO NOGUEIRA",
        turma: "2º Ano C",
        avaliados: 20,
        n1Count: 0,
        n2Count: 0,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 11,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 10.0,
        n4Perc: 0.0,
        iniciantePerc: 35.0,
        fluentePerc: 55.0,
        preTotalPerc: 10.0,
        leitoresPerc: 90.0,
        iflNum: 7.85,
        ifl: "7.85"
      },
      {
        id: "E.M. PROFª ISABEL DO CARMO NOGUEIRA__2º Ano D",
        escola: "E.M. PROFª ISABEL DO CARMO NOGUEIRA",
        turma: "2º Ano D",
        avaliados: 19,
        n1Count: 0,
        n2Count: 0,
        n3Count: 1,
        n4Count: 0,
        inicianteCount: 4,
        fluenteCount: 14,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 5.3,
        n4Perc: 0.0,
        iniciantePerc: 21.1,
        fluentePerc: 73.7,
        preTotalPerc: 5.3,
        leitoresPerc: 94.7,
        iflNum: 8.76,
        ifl: "8.76"
      }
    ]
  },
  {
    name: "E.M. JOÃO CESÁRIO",
    rawName: "E.M. JOÃO CESÁRIO",
    iflGeral: 5.43,
    iflGeralFormatted: "5.43",
    classes: [
      {
        id: "E.M. JOÃO CESÁRIO__2º Ano A",
        escola: "E.M. JOÃO CESÁRIO",
        turma: "2º Ano A",
        avaliados: 18,
        n1Count: 1,
        n2Count: 0,
        n3Count: 6,
        n4Count: 0,
        inicianteCount: 4,
        fluenteCount: 7,
        n1Perc: 5.6,
        n2Perc: 0.0,
        n3Perc: 33.3,
        n4Perc: 0.0,
        iniciantePerc: 22.2,
        fluentePerc: 38.9,
        preTotalPerc: 38.9,
        leitoresPerc: 61.1,
        iflNum: 6.06,
        ifl: "6.06"
      },
      {
        id: "E.M. JOÃO CESÁRIO__2º Ano B",
        escola: "E.M. JOÃO CESÁRIO",
        turma: "2º Ano B",
        avaliados: 16,
        n1Count: 1,
        n2Count: 0,
        n3Count: 9,
        n4Count: 0,
        inicianteCount: 3,
        fluenteCount: 3,
        n1Perc: 6.2,
        n2Perc: 0.0,
        n3Perc: 56.2,
        n4Perc: 0.0,
        iniciantePerc: 18.8,
        fluentePerc: 18.8,
        preTotalPerc: 62.5,
        leitoresPerc: 37.5,
        iflNum: 4.41,
        ifl: "4.41"
      },
      {
        id: "E.M. JOÃO CESÁRIO__2º Ano C",
        escola: "E.M. JOÃO CESÁRIO",
        turma: "2º Ano C",
        avaliados: 17,
        n1Count: 0,
        n2Count: 0,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 4,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 29.4,
        n4Perc: 0.0,
        iniciantePerc: 23.5,
        fluentePerc: 47.1,
        preTotalPerc: 29.4,
        leitoresPerc: 70.6,
        iflNum: 6.85,
        ifl: "6.85"
      },
      {
        id: "E.M. JOÃO CESÁRIO__2º Ano D",
        escola: "E.M. JOÃO CESÁRIO",
        turma: "2º Ano D",
        avaliados: 22,
        n1Count: 1,
        n2Count: 0,
        n3Count: 1,
        n4Count: 3,
        inicianteCount: 15,
        fluenteCount: 2,
        n1Perc: 4.5,
        n2Perc: 0.0,
        n3Perc: 4.5,
        n4Perc: 13.6,
        iniciantePerc: 68.2,
        fluentePerc: 9.1,
        preTotalPerc: 22.7,
        leitoresPerc: 77.3,
        iflNum: 5.20,
        ifl: "5.20"
      },
      {
        id: "E.M. JOÃO CESÁRIO__2º Ano E",
        escola: "E.M. JOÃO CESÁRIO",
        turma: "2º Ano E",
        avaliados: 22,
        n1Count: 0,
        n2Count: 0,
        n3Count: 6,
        n4Count: 0,
        inicianteCount: 10,
        fluenteCount: 6,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 27.3,
        n4Perc: 0.0,
        iniciantePerc: 45.5,
        fluentePerc: 27.3,
        preTotalPerc: 27.3,
        leitoresPerc: 72.7,
        iflNum: 6.14,
        ifl: "6.14"
      }
    ]
  },
  {
    name: "E.M. PROF. JOÃO KOLENDA LEMOS",
    rawName: "E.M. PROF. JOÃO KOLENDA LEMOS",
    iflGeral: 5.37,
    iflGeralFormatted: "5.37",
    classes: [
      {
        id: "E.M. PROF. JOÃO KOLENDA LEMOS__2º Ano A",
        escola: "E.M. PROF. JOÃO KOLENDA LEMOS",
        turma: "2º Ano A",
        avaliados: 13,
        n1Count: 6,
        n2Count: 0,
        n3Count: 0,
        n4Count: 0,
        inicianteCount: 3,
        fluenteCount: 4,
        n1Perc: 46.2,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 0.0,
        iniciantePerc: 23.1,
        fluentePerc: 30.8,
        preTotalPerc: 46.2,
        leitoresPerc: 53.8,
        iflNum: 4.46,
        ifl: "4.46"
      },
      {
        id: "E.M. PROF. JOÃO KOLENDA LEMOS__2º Ano B",
        escola: "E.M. PROF. JOÃO KOLENDA LEMOS",
        turma: "2º Ano B",
        avaliados: 12,
        n1Count: 3,
        n2Count: 1,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 5,
        fluenteCount: 1,
        n1Perc: 25.0,
        n2Perc: 8.3,
        n3Perc: 16.7,
        n4Perc: 0.0,
        iniciantePerc: 41.7,
        fluentePerc: 8.3,
        preTotalPerc: 50.0,
        leitoresPerc: 50.0,
        iflNum: 3.83,
        ifl: "3.83"
      },
      {
        id: "E.M. PROF. JOÃO KOLENDA LEMOS__2º Ano C",
        escola: "E.M. PROF. JOÃO KOLENDA LEMOS",
        turma: "2º Ano C",
        avaliados: 13,
        n1Count: 0,
        n2Count: 3,
        n3Count: 4,
        n4Count: 0,
        inicianteCount: 2,
        fluenteCount: 4,
        n1Perc: 0.0,
        n2Perc: 23.1,
        n3Perc: 30.8,
        n4Perc: 0.0,
        iniciantePerc: 15.4,
        fluentePerc: 30.8,
        preTotalPerc: 53.8,
        leitoresPerc: 46.2,
        iflNum: 5.00,
        ifl: "5.00"
      },
      {
        id: "E.M. PROF. JOÃO KOLENDA LEMOS__2º Ano D",
        escola: "E.M. PROF. JOÃO KOLENDA LEMOS",
        turma: "2º Ano D",
        avaliados: 17,
        n1Count: 2,
        n2Count: 1,
        n3Count: 0,
        n4Count: 0,
        inicianteCount: 10,
        fluenteCount: 4,
        n1Perc: 11.8,
        n2Perc: 5.9,
        n3Perc: 0.0,
        n4Perc: 0.0,
        iniciantePerc: 58.8,
        fluentePerc: 23.5,
        preTotalPerc: 17.6,
        leitoresPerc: 82.4,
        iflNum: 5.94,
        ifl: "5.94"
      },
      {
        id: "E.M. PROF. JOÃO KOLENDA LEMOS__2º Ano E",
        escola: "E.M. PROF. JOÃO KOLENDA LEMOS",
        turma: "2º Ano E",
        avaliados: 18,
        n1Count: 1,
        n2Count: 3,
        n3Count: 6,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 2,
        n1Perc: 5.6,
        n2Perc: 16.7,
        n3Perc: 33.3,
        n4Perc: 0.0,
        iniciantePerc: 33.3,
        fluentePerc: 11.1,
        preTotalPerc: 55.6,
        leitoresPerc: 44.4,
        iflNum: 4.44,
        ifl: "4.44"
      },
      {
        id: "E.M. PROF. JOÃO KOLENDA LEMOS__2º Ano F",
        escola: "E.M. PROF. JOÃO KOLENDA LEMOS",
        turma: "2º Ano F",
        avaliados: 18,
        n1Count: 1,
        n2Count: 0,
        n3Count: 1,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 9,
        n1Perc: 5.6,
        n2Perc: 0.0,
        n3Perc: 5.6,
        n4Perc: 0.0,
        iniciantePerc: 38.9,
        fluentePerc: 50.0,
        preTotalPerc: 11.1,
        leitoresPerc: 88.9,
        iflNum: 7.47,
        ifl: "7.47"
      }
    ]
  },
  {
    name: "E.M. PROF. JOAQUIM PEREIRA DA SILVA",
    rawName: "E.M. PROF. JOAQUIM PEREIRA DA SILVA",
    iflGeral: 6.82,
    iflGeralFormatted: "6.82",
    classes: [
      {
        id: "E.M. PROF. JOAQUIM PEREIRA DA SILVA__2º Ano A",
        escola: "E.M. PROF. JOAQUIM PEREIRA DA SILVA",
        turma: "2º Ano A",
        avaliados: 21,
        n1Count: 0,
        n2Count: 1,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 10,
        n1Perc: 0.0,
        n2Perc: 4.8,
        n3Perc: 14.3,
        n4Perc: 0.0,
        iniciantePerc: 33.3,
        fluentePerc: 47.6,
        preTotalPerc: 19.0,
        leitoresPerc: 81.0,
        iflNum: 7.17,
        ifl: "7.17"
      },
      {
        id: "E.M. PROF. JOAQUIM PEREIRA DA SILVA__2º Ano B",
        escola: "E.M. PROF. JOAQUIM PEREIRA DA SILVA",
        turma: "2º Ano B",
        avaliados: 20,
        n1Count: 3,
        n2Count: 0,
        n3Count: 7,
        n4Count: 0,
        inicianteCount: 5,
        fluenteCount: 5,
        n1Perc: 15.0,
        n2Perc: 0.0,
        n3Perc: 35.0,
        n4Perc: 0.0,
        iniciantePerc: 25.0,
        fluentePerc: 25.0,
        preTotalPerc: 50.0,
        leitoresPerc: 50.0,
        iflNum: 4.88,
        ifl: "4.88"
      },
      {
        id: "E.M. PROF. JOAQUIM PEREIRA DA SILVA__2º Ano C",
        escola: "E.M. PROF. JOAQUIM PEREIRA DA SILVA",
        turma: "2º Ano C",
        avaliados: 20,
        n1Count: 1,
        n2Count: 0,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 10,
        n1Perc: 5.0,
        n2Perc: 0.0,
        n3Perc: 10.0,
        n4Perc: 0.0,
        iniciantePerc: 35.0,
        fluentePerc: 50.0,
        preTotalPerc: 15.0,
        leitoresPerc: 85.0,
        iflNum: 7.35,
        ifl: "7.35"
      },
      {
        id: "E.M. PROF. JOAQUIM PEREIRA DA SILVA__2º Ano D",
        escola: "E.M. PROF. JOAQUIM PEREIRA DA SILVA",
        turma: "2º Ano D",
        avaliados: 22,
        n1Count: 0,
        n2Count: 0,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 11,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 22.7,
        n4Perc: 0.0,
        iniciantePerc: 27.3,
        fluentePerc: 50.0,
        preTotalPerc: 22.7,
        leitoresPerc: 77.3,
        iflNum: 7.20,
        ifl: "7.20"
      },
      {
        id: "E.M. PROF. JOAQUIM PEREIRA DA SILVA__2º Ano E",
        escola: "E.M. PROF. JOAQUIM PEREIRA DA SILVA",
        turma: "2º Ano E",
        avaliados: 20,
        n1Count: 1,
        n2Count: 0,
        n3Count: 0,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 12,
        n1Perc: 5.0,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 0.0,
        iniciantePerc: 35.0,
        fluentePerc: 60.0,
        preTotalPerc: 5.0,
        leitoresPerc: 95.0,
        iflNum: 8.10,
        ifl: "8.10"
      },
      {
        id: "E.M. PROF. JOAQUIM PEREIRA DA SILVA__2º Ano F",
        escola: "E.M. PROF. JOAQUIM PEREIRA DA SILVA",
        turma: "2º Ano F",
        avaliados: 21,
        n1Count: 0,
        n2Count: 0,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 10,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 14.3,
        n4Perc: 0.0,
        iniciantePerc: 47.6,
        fluentePerc: 38.1,
        preTotalPerc: 14.3,
        leitoresPerc: 85.7,
        iflNum: 6.98,
        ifl: "6.98"
      }
    ]
  },
  {
    name: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)",
    rawName: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)",
    iflGeral: 5.75,
    iflGeralFormatted: "5.75",
    classes: [
      {
        id: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)__2º Ano A",
        escola: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)",
        turma: "2º Ano A",
        avaliados: 16,
        n1Count: 1,
        n2Count: 2,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 5,
        fluenteCount: 5,
        n1Perc: 6.2,
        n2Perc: 12.5,
        n3Perc: 18.8,
        n4Perc: 0.0,
        iniciantePerc: 31.2,
        fluentePerc: 31.2,
        preTotalPerc: 37.5,
        leitoresPerc: 62.5,
        iflNum: 5.60,
        ifl: "5.60"
      },
      {
        id: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)__2º Ano B",
        escola: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)",
        turma: "2º Ano B",
        avaliados: 16,
        n1Count: 0,
        n2Count: 0,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 5,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 18.8,
        n4Perc: 0.0,
        iniciantePerc: 50.0,
        fluentePerc: 31.2,
        preTotalPerc: 18.8,
        leitoresPerc: 81.2,
        iflNum: 6.59,
        ifl: "6.59"
      },
      {
        id: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)__2º Ano C",
        escola: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)",
        turma: "2º Ano C",
        avaliados: 20,
        n1Count: 1,
        n2Count: 4,
        n3Count: 7,
        n4Count: 0,
        inicianteCount: 4,
        fluenteCount: 4,
        n1Perc: 5.0,
        n2Perc: 20.0,
        n3Perc: 35.0,
        n4Perc: 0.0,
        iniciantePerc: 20.0,
        fluentePerc: 20.0,
        preTotalPerc: 60.0,
        leitoresPerc: 40.0,
        iflNum: 4.78,
        ifl: "4.78"
      },
      {
        id: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)__2º Ano D",
        escola: "E.M. JOSÉ GONÇALVES DA SILVA (SEU JUQUINHA)",
        turma: "2º Ano D",
        avaliados: 16,
        n1Count: 0,
        n2Count: 0,
        n3Count: 7,
        n4Count: 1,
        inicianteCount: 6,
        fluenteCount: 2,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 43.8,
        n4Perc: 6.2,
        iniciantePerc: 37.5,
        fluentePerc: 12.5,
        preTotalPerc: 50.0,
        leitoresPerc: 50.0,
        iflNum: 5.19,
        ifl: "5.19"
      }
    ]
  },
  {
    name: "E.M. PROFª JULIETA REALE VIEIRA",
    rawName: "E.M. PROFª JULIETA REALE VIEIRA",
    iflGeral: 4.71,
    iflGeralFormatted: "4.71",
    classes: [
      {
        id: "E.M. PROFª JULIETA REALE VIEIRA__2º Ano A",
        escola: "E.M. PROFª JULIETA REALE VIEIRA",
        turma: "2º Ano A",
        avaliados: 16,
        n1Count: 1,
        n2Count: 0,
        n3Count: 7,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 2,
        n1Perc: 6.2,
        n2Perc: 0.0,
        n3Perc: 43.8,
        n4Perc: 0.0,
        iniciantePerc: 37.5,
        fluentePerc: 12.5,
        preTotalPerc: 50.0,
        leitoresPerc: 50.0,
        iflNum: 4.59,
        ifl: "4.59"
      },
      {
        id: "E.M. PROFª JULIETA REALE VIEIRA__2º Ano B",
        escola: "E.M. PROFª JULIETA REALE VIEIRA",
        turma: "2º Ano B",
        avaliados: 14,
        n1Count: 2,
        n2Count: 0,
        n3Count: 3,
        n4Count: 2,
        inicianteCount: 4,
        fluenteCount: 3,
        n1Perc: 14.3,
        n2Perc: 0.0,
        n3Perc: 21.4,
        n4Perc: 14.3,
        iniciantePerc: 28.6,
        fluentePerc: 21.4,
        preTotalPerc: 50.0,
        leitoresPerc: 50.0,
        iflNum: 5.30,
        ifl: "5.30"
      },
      {
        id: "E.M. PROFª JULIETA REALE VIEIRA__2º Ano C",
        escola: "E.M. PROFª JULIETA REALE VIEIRA",
        turma: "2º Ano C",
        avaliados: 20,
        n1Count: 0,
        n2Count: 1,
        n3Count: 17,
        n4Count: 0,
        inicianteCount: 0,
        fluenteCount: 2,
        n1Perc: 0.0,
        n2Perc: 5.0,
        n3Perc: 85.0,
        n4Perc: 0.0,
        iniciantePerc: 0.0,
        fluentePerc: 10.0,
        preTotalPerc: 90.0,
        leitoresPerc: 10.0,
        iflNum: 3.18,
        ifl: "3.18"
      }
    ]
  },
  {
    name: "E.M. LAURO VICENTE DE AZEVEDO",
    rawName: "E.M. LAURO VICENTE DE AZEVEDO",
    iflGeral: (6 * 16 + 5.67 * 19) / 35,
    iflGeralFormatted: "5.82",
    classes: [
      {
        id: "E.M. LAURO VICENTE DE AZEVEDO__2º Ano A",
        escola: "E.M. LAURO VICENTE DE AZEVEDO",
        turma: "2º Ano A",
        prev: 23,
        participacao: 16 / 23 * 100,
        avaliados: 16,
        n1Count: 0,
        n2Count: 5,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 1,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 31.25,
        n3Perc: 12.5,
        n4Perc: 0.0,
        iniciantePerc: 6.25,
        fluentePerc: 50.0,
        preTotalPerc: 43.75,
        leitoresPerc: 56.25,
        iflNum: 6.0,
        ifl: "6.00",
        isPendente: false
      },
      {
        id: "E.M. LAURO VICENTE DE AZEVEDO__2º Ano B",
        escola: "E.M. LAURO VICENTE DE AZEVEDO",
        turma: "2º Ano B",
        avaliados: 19,
        n1Count: 0,
        n2Count: 1,
        n3Count: 4,
        n4Count: 0,
        inicianteCount: 12,
        fluenteCount: 2,
        n1Perc: 0.0,
        n2Perc: 5.3,
        n3Perc: 21.1,
        n4Perc: 0.0,
        iniciantePerc: 63.2,
        fluentePerc: 10.5,
        preTotalPerc: 26.3,
        leitoresPerc: 73.7,
        iflNum: 5.67,
        ifl: "5.67"
      }
    ]
  },
  {
    name: "E.M. PROFª MADALENA CALTABIANO SALUM BENJAMIM",
    rawName: "E.M. PROFª MADALENA CALTABIANO SALUM BENJAMIM",
    iflGeral: 5.25,
    iflGeralFormatted: "5.25",
    classes: [
      {
        id: "E.M. PROFª MADALENA CALTABIANO SALUM BENJAMIM__2º Ano A",
        escola: "E.M. PROFª MADALENA CALTABIANO SALUM BENJAMIM",
        turma: "2º Ano A",
        avaliados: 16,
        n1Count: 0,
        n2Count: 0,
        n3Count: 0,
        n4Count: 6,
        inicianteCount: 10,
        fluenteCount: 0,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 37.5,
        iniciantePerc: 62.5,
        fluentePerc: 0.0,
        preTotalPerc: 37.5,
        leitoresPerc: 62.5,
        iflNum: 5.25,
        ifl: "5.25"
      }
    ]
  },
  {
    name: "E.M. PROFª MARIA APARECIDA ARANTES VASQUES",
    rawName: "E.M. PROFª MARIA APARECIDA ARANTES VASQUES",
    iflGeral: 6.72,
    iflGeralFormatted: "6.72",
    classes: [
      {
        id: "E.M. PROFª MARIA APARECIDA ARANTES VASQUES__2º Ano A",
        escola: "E.M. PROFª MARIA APARECIDA ARANTES VASQUES",
        turma: "2º Ano A",
        avaliados: 24,
        n1Count: 0,
        n2Count: 0,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 12,
        fluenteCount: 9,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 12.5,
        n4Perc: 0.0,
        iniciantePerc: 50.0,
        fluentePerc: 37.5,
        preTotalPerc: 12.5,
        leitoresPerc: 87.5,
        iflNum: 6.98,
        ifl: "6.98"
      },
      {
        id: "E.M. PROFª MARIA APARECIDA ARANTES VASQUES__2º Ano B",
        escola: "E.M. PROFª MARIA APARECIDA ARANTES VASQUES",
        turma: "2º Ano B",
        avaliados: 24,
        n1Count: 1,
        n2Count: 1,
        n3Count: 8,
        n4Count: 0,
        inicianteCount: 5,
        fluenteCount: 9,
        n1Perc: 4.2,
        n2Perc: 4.2,
        n3Perc: 33.3,
        n4Perc: 0.0,
        iniciantePerc: 20.8,
        fluentePerc: 37.5,
        preTotalPerc: 41.7,
        leitoresPerc: 58.3,
        iflNum: 6.27,
        ifl: "6.27"
      }
    ]
  },
  {
    name: "E.M. PROFª MARIA APARECIDA CAMARGO DE SOUZA",
    rawName: "E.M. PROFª MARIA APARECIDA C. DE SOUZA",
    iflGeral: 6.08,
    iflGeralFormatted: "6.08",
    classes: [
      {
        id: "E.M. PROFª MARIA APARECIDA CAMARGO DE SOUZA__Multisseriada Fundamental A",
        escola: "E.M. PROFª MARIA APARECIDA CAMARGO DE SOUZA",
        turma: "Multisseriada Fundamental A",
        avaliados: 6,
        n1Count: 0,
        n2Count: 0,
        n3Count: 1,
        n4Count: 0,
        inicianteCount: 4,
        fluenteCount: 1,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 16.7,
        n4Perc: 0.0,
        iniciantePerc: 66.7,
        fluentePerc: 16.7,
        preTotalPerc: 16.7,
        leitoresPerc: 83.3,
        iflNum: 6.08,
        ifl: "6.08"
      }
    ]
  },
  {
    name: "E.M. PROFª MARIA HELENA RIBEIRO VILELA",
    rawName: "E.M. PROFª MARIA HELENA RIBEIRO VILELA",
    iflGeral: 5.77,
    iflGeralFormatted: "5.77",
    classes: [
      {
        id: "E.M. PROFª MARIA HELENA RIBEIRO VILELA__2º Ano A",
        escola: "E.M. PROFª MARIA HELENA RIBEIRO VILELA",
        turma: "2º Ano A",
        avaliados: 18,
        n1Count: 1,
        n2Count: 1,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 6,
        n1Perc: 5.6,
        n2Perc: 5.6,
        n3Perc: 11.1,
        n4Perc: 0.0,
        iniciantePerc: 44.4,
        fluentePerc: 33.3,
        preTotalPerc: 22.2,
        leitoresPerc: 77.8,
        iflNum: 6.33,
        ifl: "6.33"
      },
      {
        id: "E.M. PROFª MARIA HELENA RIBEIRO VILELA__2º Ano B",
        escola: "E.M. PROFª MARIA HELENA RIBEIRO VILELA",
        turma: "2º Ano B",
        avaliados: 16,
        n1Count: 0,
        n2Count: 0,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 12,
        fluenteCount: 1,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 18.8,
        n4Perc: 0.0,
        iniciantePerc: 75.0,
        fluentePerc: 6.2,
        preTotalPerc: 18.8,
        leitoresPerc: 81.2,
        iflNum: 5.60,
        ifl: "5.60"
      },
      {
        id: "E.M. PROFª MARIA HELENA RIBEIRO VILELA__2º Ano C",
        escola: "E.M. PROFª MARIA HELENA RIBEIRO VILELA",
        turma: "2º Ano C",
        avaliados: 16,
        n1Count: 2,
        n2Count: 1,
        n3Count: 0,
        n4Count: 0,
        inicianteCount: 11,
        fluenteCount: 2,
        n1Perc: 12.5,
        n2Perc: 6.2,
        n3Perc: 0.0,
        n4Perc: 0.0,
        iniciantePerc: 68.8,
        fluentePerc: 12.5,
        preTotalPerc: 18.8,
        leitoresPerc: 81.2,
        iflNum: 5.44,
        ifl: "5.44"
      }
    ]
  },
  {
    name: "E.M. PROFª MARIA MADUREIRA SALGADO (DONA MINICA)",
    rawName: "E.M. PROFª MARIA MADUREIRA SALGADO (DONA MINICA)",
    iflGeral: 5.86,
    iflGeralFormatted: "5.86",
    classes: [
      {
        id: "E.M. PROFª MARIA MADUREIRA SALGADO (DONA MINICA)__2º Ano A",
        escola: "E.M. PROFª MARIA MADUREIRA SALGADO (DONA MINICA)",
        turma: "2º Ano A",
        avaliados: 14,
        n1Count: 0,
        n2Count: 0,
        n3Count: 4,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 3,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 28.6,
        n4Perc: 0.0,
        iniciantePerc: 50.0,
        fluentePerc: 21.4,
        preTotalPerc: 28.6,
        leitoresPerc: 71.4,
        iflNum: 5.86,
        ifl: "5.86"
      }
    ]
  },
  {
    name: "E.M. PROFª MARIA ZARA MINÉ",
    rawName: "E.M. PROFª MARIA ZARA MINÉ",
    iflGeral: 6.47,
    iflGeralFormatted: "6.47",
    classes: [
      {
        id: "E.M. PROFª MARIA ZARA MINÉ__2º Ano A",
        escola: "E.M. PROFª MARIA ZARA MINÉ",
        turma: "2º Ano A",
        avaliados: 20,
        n1Count: 1,
        n2Count: 0,
        n3Count: 1,
        n4Count: 2,
        inicianteCount: 7,
        fluenteCount: 9,
        n1Perc: 5.0,
        n2Perc: 0.0,
        n3Perc: 5.0,
        n4Perc: 10.0,
        iniciantePerc: 35.0,
        fluentePerc: 45.0,
        preTotalPerc: 20.0,
        leitoresPerc: 80.0,
        iflNum: 7.13,
        ifl: "7.13"
      },
      {
        id: "E.M. PROFª MARIA ZARA MINÉ__2º Ano B",
        escola: "E.M. PROFª MARIA ZARA MINÉ",
        turma: "2º Ano B",
        avaliados: 21,
        n1Count: 1,
        n2Count: 2,
        n3Count: 1,
        n4Count: 1,
        inicianteCount: 11,
        fluenteCount: 5,
        n1Perc: 4.8,
        n2Perc: 9.5,
        n3Perc: 4.8,
        n4Perc: 4.8,
        iniciantePerc: 52.4,
        fluentePerc: 23.8,
        preTotalPerc: 23.8,
        leitoresPerc: 76.2,
        iflNum: 5.84,
        ifl: "5.84"
      }
    ]
  },
  {
    name: "E.M. PE. MÁRIO ANTÔNIO BONOTTI",
    rawName: "E.M. PE. MÁRIO ANTÔNIO BONOTTI",
    iflGeral: 6.51,
    iflGeralFormatted: "6.51",
    classes: [
      {
        id: "E.M. PE. MÁRIO ANTÔNIO BONOTTI__2º Ano A",
        escola: "E.M. PE. MÁRIO ANTÔNIO BONOTTI",
        turma: "2º Ano A",
        avaliados: 16,
        n1Count: 0,
        n2Count: 0,
        n3Count: 1,
        n4Count: 0,
        inicianteCount: 10,
        fluenteCount: 5,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 6.2,
        n4Perc: 0.0,
        iniciantePerc: 62.5,
        fluentePerc: 31.2,
        preTotalPerc: 6.2,
        leitoresPerc: 93.8,
        iflNum: 7.03,
        ifl: "7.03"
      },
      {
        id: "E.M. PE. MÁRIO ANTÔNIO BONOTTI__2º Ano B",
        escola: "E.M. PE. MÁRIO ANTÔNIO BONOTTI",
        turma: "2º Ano B",
        avaliados: 15,
        n1Count: 2,
        n2Count: 0,
        n3Count: 6,
        n4Count: 0,
        inicianteCount: 1,
        fluenteCount: 6,
        n1Perc: 13.3,
        n2Perc: 0.0,
        n3Perc: 40.0,
        n4Perc: 0.0,
        iniciantePerc: 6.7,
        fluentePerc: 40.0,
        preTotalPerc: 53.3,
        leitoresPerc: 46.7,
        iflNum: 5.95,
        ifl: "5.95"
      }
    ]
  },
  {
    name: "E.M. PROF. MÁRIO DE ASSIS CÉSAR",
    rawName: "E.M. PROF. MÁRIO DE ASSIS CÉSAR",
    iflGeral: 5.75,
    iflGeralFormatted: "5.75",
    classes: [
      {
        id: "E.M. PROF. MÁRIO DE ASSIS CÉSAR__2º Ano A",
        escola: "E.M. PROF. MÁRIO DE ASSIS CÉSAR",
        turma: "2º Ano A",
        avaliados: 18,
        n1Count: 0,
        n2Count: 3,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 2,
        n1Perc: 0.0,
        n2Perc: 16.7,
        n3Perc: 27.8,
        n4Perc: 0.0,
        iniciantePerc: 44.4,
        fluentePerc: 11.1,
        preTotalPerc: 44.4,
        leitoresPerc: 55.6,
        iflNum: 5.47,
        ifl: "5.47"
      },
      {
        id: "E.M. PROF. MÁRIO DE ASSIS CÉSAR__2º Ano B",
        escola: "E.M. PROF. MÁRIO DE ASSIS CÉSAR",
        turma: "2º Ano B",
        avaliados: 22,
        n1Count: 0,
        n2Count: 2,
        n3Count: 9,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 5,
        n1Perc: 0.0,
        n2Perc: 9.1,
        n3Perc: 40.9,
        n4Perc: 0.0,
        iniciantePerc: 27.3,
        fluentePerc: 22.7,
        preTotalPerc: 50.0,
        leitoresPerc: 50.0,
        iflNum: 5.98,
        ifl: "5.98"
      }
    ]
  },
  {
    name: "E.M. MOACYR DE ALMEIDA",
    rawName: "E.M. MOACYR DE ALMEIDA",
    iflGeral: 6.30,
    iflGeralFormatted: "6.30",
    classes: [
      {
        id: "E.M. MOACYR DE ALMEIDA__2º Ano A",
        escola: "E.M. MOACYR DE ALMEIDA",
        turma: "2º Ano A",
        avaliados: 20,
        n1Count: 0,
        n2Count: 0,
        n3Count: 4,
        n4Count: 0,
        inicianteCount: 11,
        fluenteCount: 5,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 20.0,
        n4Perc: 0.0,
        iniciantePerc: 55.0,
        fluentePerc: 25.0,
        preTotalPerc: 20.0,
        leitoresPerc: 80.0,
        iflNum: 6.30,
        ifl: "6.30"
      }
    ]
  },
  {
    name: "E.M. ODETE CORRÊA MADUREIRA",
    rawName: "E.M. ODETE CORRÊA MADUREIRA",
    iflGeral: 5.72,
    iflGeralFormatted: "5.72",
    classes: [
      {
        id: "E.M. ODETE CORRÊA MADUREIRA__2º Ano A",
        escola: "E.M. ODETE CORRÊA MADUREIRA",
        turma: "2º Ano A",
        avaliados: 17,
        n1Count: 2,
        n2Count: 0,
        n3Count: 4,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 3,
        n1Perc: 11.8,
        n2Perc: 0.0,
        n3Perc: 23.5,
        n4Perc: 0.0,
        iniciantePerc: 47.1,
        fluentePerc: 17.6,
        preTotalPerc: 35.3,
        leitoresPerc: 64.7,
        iflNum: 5.18,
        ifl: "5.18"
      },
      {
        id: "E.M. ODETE CORRÊA MADUREIRA__2º Ano B",
        escola: "E.M. ODETE CORRÊA MADUREIRA",
        turma: "2º Ano B",
        avaliados: 17,
        n1Count: 0,
        n2Count: 3,
        n3Count: 4,
        n4Count: 0,
        inicianteCount: 5,
        fluenteCount: 5,
        n1Perc: 0.0,
        n2Perc: 17.6,
        n3Perc: 23.5,
        n4Perc: 0.0,
        iniciantePerc: 29.4,
        fluentePerc: 29.4,
        preTotalPerc: 41.2,
        leitoresPerc: 58.8,
        iflNum: 6.06,
        ifl: "6.06"
      },
      {
        id: "E.M. ODETE CORRÊA MADUREIRA__2º Ano C",
        escola: "E.M. ODETE CORRÊA MADUREIRA",
        turma: "2º Ano C",
        avaliados: 19,
        n1Count: 3,
        n2Count: 1,
        n3Count: 6,
        n4Count: 0,
        inicianteCount: 5,
        fluenteCount: 4,
        n1Perc: 15.8,
        n2Perc: 5.3,
        n3Perc: 31.6,
        n4Perc: 0.0,
        iniciantePerc: 26.3,
        fluentePerc: 21.1,
        preTotalPerc: 52.6,
        leitoresPerc: 47.4,
        iflNum: 5.84,
        ifl: "5.84"
      }
    ]
  },
  {
    name: "E.M. PROF. ORLANDO PIRES",
    rawName: "E.M. PROF. ORLANDO PIRES",
    iflGeral: 6.44,
    iflGeralFormatted: "6.44",
    classes: [
      {
        id: "E.M. PROF. ORLANDO PIRES__2º Ano A",
        escola: "E.M. PROF. ORLANDO PIRES",
        turma: "2º Ano A",
        avaliados: 13,
        n1Count: 0,
        n2Count: 0,
        n3Count: 0,
        n4Count: 3,
        inicianteCount: 8,
        fluenteCount: 2,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 23.1,
        iniciantePerc: 61.5,
        fluentePerc: 15.4,
        preTotalPerc: 23.1,
        leitoresPerc: 76.9,
        iflNum: 6.15,
        ifl: "6.15"
      },
      {
        id: "E.M. PROF. ORLANDO PIRES__2º Ano B",
        escola: "E.M. PROF. ORLANDO PIRES",
        turma: "2º Ano B",
        avaliados: 14,
        n1Count: 1,
        n2Count: 0,
        n3Count: 1,
        n4Count: 1,
        inicianteCount: 8,
        fluenteCount: 3,
        n1Perc: 7.1,
        n2Perc: 0.0,
        n3Perc: 7.1,
        n4Perc: 7.1,
        iniciantePerc: 57.1,
        fluentePerc: 21.4,
        preTotalPerc: 21.4,
        leitoresPerc: 78.6,
        iflNum: 6.71,
        ifl: "6.71"
      }
    ]
  },
  {
    name: "E.M. PADRE ZEZINHO",
    rawName: "E.M. PADRE ZEZINHO",
    iflGeral: 7.04,
    iflGeralFormatted: "7.04",
    classes: [
      {
        id: "E.M. PADRE ZEZINHO__2º Ano A",
        escola: "E.M. PADRE ZEZINHO",
        turma: "2º Ano A",
        avaliados: 17,
        n1Count: 1,
        n2Count: 0,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 4,
        fluenteCount: 10,
        n1Perc: 5.9,
        n2Perc: 0.0,
        n3Perc: 11.8,
        n4Perc: 0.0,
        iniciantePerc: 23.5,
        fluentePerc: 58.8,
        preTotalPerc: 17.6,
        leitoresPerc: 82.4,
        iflNum: 7.59,
        ifl: "7.59"
      },
      {
        id: "E.M. PADRE ZEZINHO__2º Ano B",
        escola: "E.M. PADRE ZEZINHO",
        turma: "2º Ano B",
        avaliados: 20,
        n1Count: 0,
        n2Count: 0,
        n3Count: 1,
        n4Count: 1,
        inicianteCount: 10,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 5.0,
        n4Perc: 5.0,
        iniciantePerc: 50.0,
        fluentePerc: 40.0,
        preTotalPerc: 10.0,
        leitoresPerc: 90.0,
        iflNum: 7.33,
        ifl: "7.33"
      },
      {
        id: "E.M. PADRE ZEZINHO__2º Ano C",
        escola: "E.M. PADRE ZEZINHO",
        turma: "2º Ano C",
        avaliados: 17,
        n1Count: 2,
        n2Count: 0,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 7,
        n1Perc: 11.8,
        n2Perc: 0.0,
        n3Perc: 11.8,
        n4Perc: 0.0,
        iniciantePerc: 35.3,
        fluentePerc: 41.2,
        preTotalPerc: 23.5,
        leitoresPerc: 76.5,
        iflNum: 6.53,
        ifl: "6.53"
      }
    ]
  },
  {
    name: "E.M. PROF. PAULO FREIRE",
    rawName: "E.M. PROF. PAULO FREIRE",
    iflGeral: 9.08,
    iflGeralFormatted: "9.08",
    classes: [
      {
        id: "E.M. PROF. PAULO FREIRE__2º Ano A",
        escola: "E.M. PROF. PAULO FREIRE",
        turma: "2º Ano A",
        avaliados: 14,
        n1Count: 0,
        n2Count: 0,
        n3Count: 0,
        n4Count: 1,
        inicianteCount: 3,
        fluenteCount: 10,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 7.1,
        iniciantePerc: 21.4,
        fluentePerc: 71.4,
        preTotalPerc: 7.1,
        leitoresPerc: 92.9,
        iflNum: 8.71,
        ifl: "8.71"
      },
      {
        id: "E.M. PROF. PAULO FREIRE__2º Ano B",
        escola: "E.M. PROF. PAULO FREIRE",
        turma: "2º Ano B",
        avaliados: 12,
        n1Count: 0,
        n2Count: 0,
        n3Count: 0,
        n4Count: 0,
        inicianteCount: 1,
        fluenteCount: 11,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 0.0,
        iniciantePerc: 8.3,
        fluentePerc: 91.7,
        preTotalPerc: 0.0,
        leitoresPerc: 100.0,
        iflNum: 9.48,
        ifl: "9.48"
      }
    ]
  },
  {
    name: "E.M. PROFª RACHEL DE AGUIAR LOBERTO",
    rawName: "E.M. PROFª RACHEL DE AGUIAR LOBERTO",
    iflGeral: 6.82,
    iflGeralFormatted: "6.82",
    classes: [
      {
        id: "E.M. PROFª RACHEL DE AGUIAR LOBERTO__2º Ano A",
        escola: "E.M. PROFª RACHEL DE AGUIAR LOBERTO",
        turma: "2º Ano A",
        avaliados: 24,
        n1Count: 0,
        n2Count: 0,
        n3Count: 6,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 12,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 25.0,
        n4Perc: 0.0,
        iniciantePerc: 25.0,
        fluentePerc: 50.0,
        preTotalPerc: 25.0,
        leitoresPerc: 75.0,
        iflNum: 7.13,
        ifl: "7.13"
      },
      {
        id: "E.M. PROFª RACHEL DE AGUIAR LOBERTO__2º Ano B",
        escola: "E.M. PROFª RACHEL DE AGUIAR LOBERTO",
        turma: "2º Ano B",
        avaliados: 23,
        n1Count: 0,
        n2Count: 0,
        n3Count: 6,
        n4Count: 0,
        inicianteCount: 10,
        fluenteCount: 7,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 26.1,
        n4Perc: 0.0,
        iniciantePerc: 43.5,
        fluentePerc: 30.4,
        preTotalPerc: 26.1,
        leitoresPerc: 73.9,
        iflNum: 6.50,
        ifl: "6.50"
      }
    ]
  },
  {
    name: "E.M. PROFª RUTH AZEVEDO ROMEIRO",
    rawName: "E.M. PROFª RUTH AZEVEDO ROMEIRO",
    iflGeral: 5.64,
    iflGeralFormatted: "5.64",
    classes: [
      {
        id: "E.M. PROFª RUTH AZEVEDO ROMEIRO__2º Ano A",
        escola: "E.M. PROFª RUTH AZEVEDO ROMEIRO",
        turma: "2º Ano A",
        avaliados: 21,
        n1Count: 1,
        n2Count: 4,
        n3Count: 4,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 5,
        n1Perc: 4.8,
        n2Perc: 19.0,
        n3Perc: 19.0,
        n4Perc: 0.0,
        iniciantePerc: 33.3,
        fluentePerc: 23.8,
        preTotalPerc: 42.9,
        leitoresPerc: 57.1,
        iflNum: 5.64,
        ifl: "5.64"
      },
      {
        id: "E.M. PROFª RUTH AZEVEDO ROMEIRO__2º Ano B",
        escola: "E.M. PROFª RUTH AZEVEDO ROMEIRO",
        turma: "2º Ano B",
        avaliados: 20,
        n1Count: 2,
        n2Count: 1,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 5,
        n1Perc: 10.0,
        n2Perc: 5.0,
        n3Perc: 25.0,
        n4Perc: 0.0,
        iniciantePerc: 35.0,
        fluentePerc: 25.0,
        preTotalPerc: 40.0,
        leitoresPerc: 60.0,
        iflNum: 5.65,
        ifl: "5.65"
      }
    ]
  },
  {
    name: "E.M. PROF. VITO ARDITO",
    rawName: "E.M. PROF. VITO ARDITO",
    iflGeral: 6.34,
    iflGeralFormatted: "6.34",
    classes: [
      {
        id: "E.M. PROF. VITO ARDITO__2º Ano A",
        escola: "E.M. PROF. VITO ARDITO",
        turma: "2º Ano A",
        avaliados: 21,
        n1Count: 1,
        n2Count: 1,
        n3Count: 0,
        n4Count: 1,
        inicianteCount: 11,
        fluenteCount: 7,
        n1Perc: 4.8,
        n2Perc: 4.8,
        n3Perc: 0.0,
        n4Perc: 4.8,
        iniciantePerc: 52.4,
        fluentePerc: 33.3,
        preTotalPerc: 14.3,
        leitoresPerc: 85.7,
        iflNum: 6.50,
        ifl: "6.50"
      },
      {
        id: "E.M. PROF. VITO ARDITO__2º Ano B",
        escola: "E.M. PROF. VITO ARDITO",
        turma: "2º Ano B",
        avaliados: 18,
        n1Count: 1,
        n2Count: 0,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 4,
        n1Perc: 5.6,
        n2Perc: 0.0,
        n3Perc: 27.8,
        n4Perc: 0.0,
        iniciantePerc: 44.4,
        fluentePerc: 22.2,
        preTotalPerc: 33.3,
        leitoresPerc: 66.7,
        iflNum: 6.17,
        ifl: "6.17"
      }
    ]
  },
  {
    name: "E.M. PROFª YVONE APARECIDA ARANTES CORRÊA",
    rawName: "E.M. PROFª YVONE APARECIDA ARANTES CORRÊA",
    iflGeral: 5.25,
    iflGeralFormatted: "5.25",
    classes: [
      {
        id: "E.M. PROFª YVONE APARECIDA ARANTES CORRÊA__2º Ano A",
        escola: "E.M. PROFª YVONE APARECIDA ARANTES CORRÊA",
        turma: "2º Ano A",
        avaliados: 18,
        n1Count: 1,
        n2Count: 2,
        n3Count: 0,
        n4Count: 2,
        inicianteCount: 11,
        fluenteCount: 2,
        n1Perc: 5.6,
        n2Perc: 11.1,
        n3Perc: 0.0,
        n4Perc: 11.1,
        iniciantePerc: 61.1,
        fluentePerc: 11.1,
        preTotalPerc: 27.8,
        leitoresPerc: 72.2,
        iflNum: 5.25,
        ifl: "5.25"
      }
    ]
  },
  {
    name: "E.M. SERAFIM FERREIRA",
    rawName: "E.M. SERAFIM FERREIRA",
    iflGeral: 6.30,
    iflGeralFormatted: "6.30",
    classes: [
      {
        id: "E.M. SERAFIM FERREIRA__2º ANO A",
        escola: "E.M. SERAFIM FERREIRA",
        turma: "2º ANO A",
        prev: 25,
        avaliados: 23,
        participacao: 92.0,
        n1Count: 0,
        n2Count: 0,
        n3Count: 2,
        n4Count: 1,
        inicianteCount: 9,
        fluenteCount: 11,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 8.7,
        n4Perc: 4.3,
        iniciantePerc: 39.1,
        fluentePerc: 47.8,
        preTotalPerc: 13.0,
        leitoresPerc: 86.9,
        iflNum: 7.52,
        ifl: "7.52"
      },
      {
        id: "E.M. SERAFIM FERREIRA__2º ANO B",
        escola: "E.M. SERAFIM FERREIRA",
        turma: "2º ANO B",
        prev: 22,
        avaliados: 19,
        participacao: 86.4,
        n1Count: 2,
        n2Count: 0,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 6,
        n1Perc: 10.5,
        n2Perc: 0.0,
        n3Perc: 26.3,
        n4Perc: 0.0,
        iniciantePerc: 31.6,
        fluentePerc: 31.6,
        preTotalPerc: 36.8,
        leitoresPerc: 63.2,
        iflNum: 5.71,
        ifl: "5.71"
      },
      {
        id: "E.M. SERAFIM FERREIRA__2º ANO C",
        escola: "E.M. SERAFIM FERREIRA",
        turma: "2º ANO C",
        prev: 21,
        avaliados: 19,
        participacao: 90.5,
        n1Count: 2,
        n2Count: 2,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 5,
        fluenteCount: 7,
        n1Perc: 10.5,
        n2Perc: 10.5,
        n3Perc: 15.8,
        n4Perc: 0.0,
        iniciantePerc: 26.3,
        fluentePerc: 36.8,
        preTotalPerc: 36.8,
        leitoresPerc: 63.1,
        iflNum: 5.76,
        ifl: "5.76"
      }
    ]
  },
  {
    name: "E.M. PROFª REGINA CÉLIA MADUREIRA DE SOUZA LIMA",
    rawName: "E.M. PROFª REGINA CÉLIA MADUREIRA DE SOUZA LIMA",
    iflGeral: 5.92,
    iflGeralFormatted: "5.92",
    classes: [
      {
        id: "E.M. PROFª REGINA CÉLIA MADUREIRA DE SOUZA LIMA__2º ANO A",
        escola: "E.M. PROFª REGINA CÉLIA MADUREIRA DE SOUZA LIMA",
        turma: "2º ANO A",
        prev: 23,
        avaliados: 21,
        participacao: 91.3,
        n1Count: 1,
        n2Count: 0,
        n3Count: 0,
        n4Count: 0,
        inicianteCount: 11,
        fluenteCount: 9,
        n1Perc: 4.8,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 0.0,
        iniciantePerc: 52.4,
        fluentePerc: 42.9,
        preTotalPerc: 4.8,
        leitoresPerc: 95.3,
        iflNum: 7.43,
        ifl: "7.43"
      },
      {
        id: "E.M. PROFª REGINA CÉLIA MADUREIRA DE SOUZA LIMA__2º ANO B",
        escola: "E.M. PROFª REGINA CÉLIA MADUREIRA DE SOUZA LIMA",
        turma: "2º ANO B",
        prev: 18,
        avaliados: 14,
        participacao: 77.8,
        n1Count: 1,
        n2Count: 4,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 0,
        n1Perc: 7.1,
        n2Perc: 28.6,
        n3Perc: 14.3,
        n4Perc: 0.0,
        iniciantePerc: 50.0,
        fluentePerc: 0.0,
        preTotalPerc: 50.0,
        leitoresPerc: 50.0,
        iflNum: 3.64,
        ifl: "3.64"
      },
      {
        id: "E.M. PROFª REGINA CÉLIA MADUREIRA DE SOUZA LIMA__2º ANO C",
        escola: "E.M. PROFª REGINA CÉLIA MADUREIRA DE SOUZA LIMA",
        turma: "2º ANO C",
        prev: 28,
        avaliados: 24,
        participacao: 85.7,
        n1Count: 2,
        n2Count: 0,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 14,
        fluenteCount: 6,
        n1Perc: 8.3,
        n2Perc: 0.0,
        n3Perc: 8.3,
        n4Perc: 0.0,
        iniciantePerc: 58.3,
        fluentePerc: 25.0,
        preTotalPerc: 16.6,
        leitoresPerc: 83.3,
        iflNum: 6.21,
        ifl: "6.21"
      }
    ]
  },
  {
    name: "E.M. PROFª GILDA PIORINI MOLICA",
    rawName: "E.M. PROFª GILDA PIORINI MOLICA",
    iflGeral: 7.29,
    iflGeralFormatted: "7.29",
    classes: [
      {
        id: "E.M. PROFª GILDA PIORINI MOLICA__2º ANO A",
        escola: "E.M. PROFª GILDA PIORINI MOLICA",
        turma: "2º ANO A",
        prev: 21,
        avaliados: 15,
        participacao: 71.4,
        n1Count: 0,
        n2Count: 1,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 4,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 6.7,
        n3Perc: 13.3,
        n4Perc: 0.0,
        iniciantePerc: 26.7,
        fluentePerc: 53.3,
        preTotalPerc: 20.0,
        leitoresPerc: 80.0,
        iflNum: 7.33,
        ifl: "7.33"
      },
      {
        id: "E.M. PROFª GILDA PIORINI MOLICA__2º ANO B",
        escola: "E.M. PROFª GILDA PIORINI MOLICA",
        turma: "2º ANO B",
        prev: 19,
        avaliados: 18,
        participacao: 94.7,
        n1Count: 2,
        n2Count: 0,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 2,
        fluenteCount: 11,
        n1Perc: 11.1,
        n2Perc: 0.0,
        n3Perc: 16.7,
        n4Perc: 0.0,
        iniciantePerc: 11.1,
        fluentePerc: 61.1,
        preTotalPerc: 27.8,
        leitoresPerc: 72.2,
        iflNum: 7.20,
        ifl: "7.20"
      },
      {
        id: "E.M. PROFª GILDA PIORINI MOLICA__2º ANO C",
        escola: "E.M. PROFª GILDA PIORINI MOLICA",
        turma: "2º ANO C",
        prev: 18,
        avaliados: 18,
        participacao: 100.0,
        n1Count: 1,
        n2Count: 0,
        n3Count: 0,
        n4Count: 1,
        inicianteCount: 9,
        fluenteCount: 7,
        n1Perc: 5.6,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 5.6,
        iniciantePerc: 50.0,
        fluentePerc: 38.9,
        preTotalPerc: 11.2,
        leitoresPerc: 88.9,
        iflNum: 7.34,
        ifl: "7.34"
      }
    ]
  },
  {
    name: "E.M. PROF. ELIAS BARGIS MATHIAS",
    rawName: "E.M. PROF. ELIAS BARGIS MATHIAS",
    iflGeral: 6.30,
    iflGeralFormatted: "6.30",
    classes: [
      {
        id: "E.M. PROF. ELIAS BARGIS MATHIAS__2º ANO A",
        escola: "E.M. PROF. ELIAS BARGIS MATHIAS",
        turma: "2º ANO A",
        prev: 22,
        avaliados: 21,
        participacao: 95.5,
        n1Count: 0,
        n2Count: 0,
        n3Count: 9,
        n4Count: 0,
        inicianteCount: 9,
        fluenteCount: 3,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 42.9,
        n4Perc: 0.0,
        iniciantePerc: 42.9,
        fluentePerc: 14.3,
        preTotalPerc: 42.9,
        leitoresPerc: 57.2,
        iflNum: 5.07,
        ifl: "5.07"
      },
      {
        id: "E.M. PROF. ELIAS BARGIS MATHIAS__2º ANO B",
        escola: "E.M. PROF. ELIAS BARGIS MATHIAS",
        turma: "2º ANO B",
        prev: 22,
        avaliados: 21,
        participacao: 95.5,
        n1Count: 1,
        n2Count: 1,
        n3Count: 1,
        n4Count: 0,
        inicianteCount: 14,
        fluenteCount: 4,
        n1Perc: 4.8,
        n2Perc: 4.8,
        n3Perc: 4.8,
        n4Perc: 0.0,
        iniciantePerc: 66.7,
        fluentePerc: 19.0,
        preTotalPerc: 14.4,
        leitoresPerc: 85.7,
        iflNum: 6.07,
        ifl: "6.07"
      },
      {
        id: "E.M. PROF. ELIAS BARGIS MATHIAS__2º ANO C",
        escola: "E.M. PROF. ELIAS BARGIS MATHIAS",
        turma: "2º ANO C",
        prev: 25,
        avaliados: 23,
        participacao: 92.0,
        n1Count: 0,
        n2Count: 0,
        n3Count: 1,
        n4Count: 2,
        inicianteCount: 12,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 4.3,
        n4Perc: 8.7,
        iniciantePerc: 52.2,
        fluentePerc: 34.8,
        preTotalPerc: 13.0,
        leitoresPerc: 87.0,
        iflNum: 7.07,
        ifl: "7.07"
      },
      {
        id: "E.M. PROF. ELIAS BARGIS MATHIAS__2º ANO D",
        escola: "E.M. PROF. ELIAS BARGIS MATHIAS",
        turma: "2º ANO D",
        prev: 28,
        avaliados: 24,
        participacao: 85.7,
        n1Count: 0,
        n2Count: 0,
        n3Count: 3,
        n4Count: 1,
        inicianteCount: 18,
        fluenteCount: 2,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 12.5,
        n4Perc: 4.2,
        iniciantePerc: 75.0,
        fluentePerc: 8.3,
        preTotalPerc: 16.7,
        leitoresPerc: 83.3,
        iflNum: 5.81,
        ifl: "5.81"
      }
    ]
  },
  {
    name: "E.M. DR. FRANCISCO DE ASSIS CÉSAR",
    rawName: "E.M. DR. FRANCISCO DE ASSIS CÉSAR",
    iflGeral: 6.13,
    iflGeralFormatted: "6.13",
    classes: [
      {
        id: "E.M. DR. FRANCISCO DE ASSIS CÉSAR__2º ANO A",
        escola: "E.M. DR. FRANCISCO DE ASSIS CÉSAR",
        turma: "2º ANO A",
        prev: 22,
        avaliados: 15,
        participacao: 68.2,
        n1Count: 2,
        n2Count: 2,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 5,
        fluenteCount: 3,
        n1Perc: 13.3,
        n2Perc: 13.3,
        n3Perc: 20.0,
        n4Perc: 0.0,
        iniciantePerc: 33.3,
        fluentePerc: 20.0,
        preTotalPerc: 46.6,
        leitoresPerc: 53.3,
        iflNum: 4.63,
        ifl: "4.63"
      },
      {
        id: "E.M. DR. FRANCISCO DE ASSIS CÉSAR__2º ANO B",
        escola: "E.M. DR. FRANCISCO DE ASSIS CÉSAR",
        turma: "2º ANO B",
        prev: 22,
        avaliados: 14,
        participacao: 63.6,
        n1Count: 2,
        n2Count: 0,
        n3Count: 1,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 4,
        n1Perc: 14.3,
        n2Perc: 0.0,
        n3Perc: 7.1,
        n4Perc: 0.0,
        iniciantePerc: 50.0,
        fluentePerc: 28.6,
        preTotalPerc: 21.4,
        leitoresPerc: 78.6,
        iflNum: 6.04,
        ifl: "6.04"
      },
      {
        id: "E.M. DR. FRANCISCO DE ASSIS CÉSAR__2º ANO C",
        escola: "E.M. DR. FRANCISCO DE ASSIS CÉSAR",
        turma: "2º ANO C",
        prev: 28,
        avaliados: 17,
        participacao: 60.7,
        n1Count: 1,
        n2Count: 1,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 4,
        fluenteCount: 9,
        n1Perc: 5.9,
        n2Perc: 5.9,
        n3Perc: 11.8,
        n4Perc: 0.0,
        iniciantePerc: 23.5,
        fluentePerc: 52.9,
        preTotalPerc: 23.6,
        leitoresPerc: 76.4,
        iflNum: 7.06,
        ifl: "7.06"
      }
    ]
  },
  {
    name: "E.M. FÉLIX ADIB MIGUEL",
    rawName: "E.M. FÉLIX ADIB MIGUEL",
    iflGeral: 6.90,
    iflGeralFormatted: "6.90",
    classes: [
      {
        id: "E.M. FÉLIX ADIB MIGUEL__2º ANO A",
        escola: "E.M. FÉLIX ADIB MIGUEL",
        turma: "2º ANO A",
        prev: 25,
        avaliados: 22,
        participacao: 88.0,
        n1Count: 1,
        n2Count: 1,
        n3Count: 1,
        n4Count: 2,
        inicianteCount: 7,
        fluenteCount: 10,
        n1Perc: 4.5,
        n2Perc: 4.5,
        n3Perc: 4.5,
        n4Perc: 9.1,
        iniciantePerc: 31.8,
        fluentePerc: 45.5,
        preTotalPerc: 22.6,
        leitoresPerc: 77.3,
        iflNum: 6.98,
        ifl: "6.98"
      },
      {
        id: "E.M. FÉLIX ADIB MIGUEL__2º ANO B",
        escola: "E.M. FÉLIX ADIB MIGUEL",
        turma: "2º ANO B",
        prev: 23,
        avaliados: 20,
        participacao: 87.0,
        n1Count: 0,
        n2Count: 1,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 10,
        fluenteCount: 7,
        n1Perc: 0.0,
        n2Perc: 5.0,
        n3Perc: 10.0,
        n4Perc: 0.0,
        iniciantePerc: 50.0,
        fluentePerc: 35.0,
        preTotalPerc: 15.0,
        leitoresPerc: 85.0,
        iflNum: 6.80,
        ifl: "6.80"
      }
    ]
  },
  {
    name: "E.M. DULCE PEDROSA ROMEIRO GUIMARÃES",
    rawName: "E.M. DULCE PEDROSA ROMEIRO GUIMARÃES",
    iflGeral: 7.07,
    iflGeralFormatted: "7.07",
    classes: [
      {
        id: "E.M. DULCE PEDROSA ROMEIRO GUIMARÃES__2º ANO A",
        escola: "E.M. DULCE PEDROSA ROMEIRO GUIMARÃES",
        turma: "2º ANO A",
        prev: 24,
        avaliados: 18,
        participacao: 75.0,
        n1Count: 0,
        n2Count: 0,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 7,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 27.8,
        n4Perc: 0.0,
        iniciantePerc: 33.3,
        fluentePerc: 38.9,
        preTotalPerc: 27.8,
        leitoresPerc: 72.2,
        iflNum: 6.58,
        ifl: "6.58"
      },
      {
        id: "E.M. DULCE PEDROSA ROMEIRO GUIMARÃES__2º ANO B",
        escola: "E.M. DULCE PEDROSA ROMEIRO GUIMARÃES",
        turma: "2º ANO B",
        prev: 20,
        avaliados: 19,
        participacao: 95.0,
        n1Count: 0,
        n2Count: 0,
        n3Count: 1,
        n4Count: 0,
        inicianteCount: 10,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 5.3,
        n4Perc: 0.0,
        iniciantePerc: 52.6,
        fluentePerc: 42.1,
        preTotalPerc: 5.3,
        leitoresPerc: 94.7,
        iflNum: 7.50,
        ifl: "7.50"
      }
    ]
  },
  {
    name: "E.M. AUGUSTO CÉSAR RIBEIRO",
    rawName: "E.M. AUGUSTO CÉSAR RIBEIRO",
    iflGeral: 6.45,
    iflGeralFormatted: "6.45",
    classes: [
      {
        id: "E.M. AUGUSTO CÉSAR RIBEIRO__2º ANO A",
        escola: "E.M. AUGUSTO CÉSAR RIBEIRO",
        turma: "2º ANO A",
        prev: 20,
        avaliados: 19,
        participacao: 95.0,
        n1Count: 0,
        n2Count: 0,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 11,
        fluenteCount: 5,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 15.8,
        n4Perc: 0.0,
        iniciantePerc: 57.9,
        fluentePerc: 26.3,
        preTotalPerc: 15.8,
        leitoresPerc: 84.2,
        iflNum: 6.50,
        ifl: "6.50"
      },
      {
        id: "E.M. AUGUSTO CÉSAR RIBEIRO__2º ANO B",
        escola: "E.M. AUGUSTO CÉSAR RIBEIRO",
        turma: "2º ANO B",
        prev: 23,
        avaliados: 20,
        participacao: 87.0,
        n1Count: 1,
        n2Count: 0,
        n3Count: 0,
        n4Count: 3,
        inicianteCount: 11,
        fluenteCount: 5,
        n1Perc: 5.0,
        n2Perc: 0.0,
        n3Perc: 0.0,
        n4Perc: 15.0,
        iniciantePerc: 55.0,
        fluentePerc: 25.0,
        preTotalPerc: 20.0,
        leitoresPerc: 80.0,
        iflNum: 6.40,
        ifl: "6.40"
      }
    ]
  },
  {
    name: "E.M. DOUTOR ÂNGELO PAZ DA SILVA",
    rawName: "E.M. DOUTOR ÂNGELO PAZ DA SILVA",
    iflGeral: 6.94,
    iflGeralFormatted: "6.94",
    classes: [
      {
        id: "E.M. DOUTOR ÂNGELO PAZ DA SILVA__2º ANO A",
        escola: "E.M. DOUTOR ÂNGELO PAZ DA SILVA",
        turma: "2º ANO A",
        prev: 16,
        avaliados: 16,
        participacao: 100.0,
        n1Count: 0,
        n2Count: 0,
        n3Count: 2,
        n4Count: 1,
        inicianteCount: 9,
        fluenteCount: 4,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 12.5,
        n4Perc: 6.3,
        iniciantePerc: 56.3,
        fluentePerc: 25.0,
        preTotalPerc: 18.8,
        leitoresPerc: 81.3,
        iflNum: 6.44,
        ifl: "6.44"
      },
      {
        id: "E.M. DOUTOR ÂNGELO PAZ DA SILVA__2º ANO B",
        escola: "E.M. DOUTOR ÂNGELO PAZ DA SILVA",
        turma: "2º ANO B",
        prev: 16,
        avaliados: 14,
        participacao: 87.5,
        n1Count: 1,
        n2Count: 0,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 3,
        fluenteCount: 7,
        n1Perc: 7.1,
        n2Perc: 0.0,
        n3Perc: 21.4,
        n4Perc: 0.0,
        iniciantePerc: 21.4,
        fluentePerc: 50.0,
        preTotalPerc: 28.5,
        leitoresPerc: 71.4,
        iflNum: 6.82,
        ifl: "6.82"
      },
      {
        id: "E.M. DOUTOR ÂNGELO PAZ DA SILVA__2º ANO C",
        escola: "E.M. DOUTOR ÂNGELO PAZ DA SILVA",
        turma: "2º ANO C",
        prev: 19,
        avaliados: 15,
        participacao: 78.9,
        n1Count: 0,
        n2Count: 0,
        n3Count: 2,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 5,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 13.3,
        n4Perc: 0.0,
        iniciantePerc: 53.3,
        fluentePerc: 33.3,
        preTotalPerc: 13.3,
        leitoresPerc: 86.7,
        iflNum: 7.53,
        ifl: "7.53"
      }
    ]
  },
  {
    name: "E.M. DR. ANDRÉ FRANCO MONTORO",
    rawName: "E.M. DR. ANDRÉ FRANCO MONTORO",
    iflGeral: 6.27,
    iflGeralFormatted: "6.27",
    classes: [
      {
        id: "E.M. DR. ANDRÉ FRANCO MONTORO__2º ANO A",
        escola: "E.M. DR. ANDRÉ FRANCO MONTORO",
        turma: "2º ANO A",
        prev: 23,
        avaliados: 18,
        participacao: 78.3,
        n1Count: 3,
        n2Count: 0,
        n3Count: 1,
        n4Count: 2,
        inicianteCount: 9,
        fluenteCount: 3,
        n1Perc: 16.7,
        n2Perc: 0.0,
        n3Perc: 5.6,
        n4Perc: 11.1,
        iniciantePerc: 50.0,
        fluentePerc: 16.7,
        preTotalPerc: 33.4,
        leitoresPerc: 66.7,
        iflNum: 5.25,
        ifl: "5.25"
      },
      {
        id: "E.M. DR. ANDRÉ FRANCO MONTORO__2º ANO B",
        escola: "E.M. DR. ANDRÉ FRANCO MONTORO",
        turma: "2º ANO B",
        prev: 21,
        avaliados: 18,
        participacao: 85.7,
        n1Count: 0,
        n2Count: 0,
        n3Count: 2,
        n4Count: 2,
        inicianteCount: 6,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 11.1,
        n4Perc: 11.1,
        iniciantePerc: 33.3,
        fluentePerc: 44.4,
        preTotalPerc: 22.2,
        leitoresPerc: 77.8,
        iflNum: 7.17,
        ifl: "7.17"
      },
      {
        id: "E.M. DR. ANDRÉ FRANCO MONTORO__2º ANO C",
        escola: "E.M. DR. ANDRÉ FRANCO MONTORO",
        turma: "2º ANO C",
        prev: 22,
        avaliados: 17,
        participacao: 77.3,
        n1Count: 1,
        n2Count: 2,
        n3Count: 1,
        n4Count: 0,
        inicianteCount: 12,
        fluenteCount: 1,
        n1Perc: 5.9,
        n2Perc: 11.8,
        n3Perc: 5.9,
        n4Perc: 0.0,
        iniciantePerc: 70.6,
        fluentePerc: 5.9,
        preTotalPerc: 23.6,
        leitoresPerc: 76.5,
        iflNum: 5.24,
        ifl: "5.24"
      }
    ]
  },
  {
    name: "E.M. PROFESSOR ALEXANDRE MACHADO SALGADO",
    rawName: "E.M. PROFESSOR ALEXANDRE MACHADO SALGADO",
    iflGeral: 5.01,
    iflGeralFormatted: "5.01",
    classes: [
      {
        id: "E.M. PROFESSOR ALEXANDRE MACHADO SALGADO__2º ANO A",
        escola: "E.M. PROFESSOR ALEXANDRE MACHADO SALGADO",
        turma: "2º ANO A",
        prev: 20,
        avaliados: 17,
        participacao: 85.0,
        n1Count: 1,
        n2Count: 0,
        n3Count: 12,
        n4Count: 0,
        inicianteCount: 0,
        fluenteCount: 4,
        n1Perc: 5.9,
        n2Perc: 0.0,
        n3Perc: 70.6,
        n4Perc: 0.0,
        iniciantePerc: 0.0,
        fluentePerc: 23.5,
        preTotalPerc: 76.5,
        leitoresPerc: 23.5,
        iflNum: 4.12,
        ifl: "4.12"
      },
      {
        id: "E.M. PROFESSOR ALEXANDRE MACHADO SALGADO__2º ANO B",
        escola: "E.M. PROFESSOR ALEXANDRE MACHADO SALGADO",
        turma: "2º ANO B",
        prev: 23,
        avaliados: 17,
        participacao: 73.9,
        n1Count: 1,
        n2Count: 0,
        n3Count: 3,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 5,
        n1Perc: 5.9,
        n2Perc: 0.0,
        n3Perc: 17.6,
        n4Perc: 0.0,
        iniciantePerc: 47.1,
        fluentePerc: 29.4,
        preTotalPerc: 23.5,
        leitoresPerc: 76.5,
        iflNum: 6.21,
        ifl: "6.21"
      },
      {
        id: "E.M. PROFESSOR ALEXANDRE MACHADO SALGADO__2º ANO C",
        escola: "E.M. PROFESSOR ALEXANDRE MACHADO SALGADO",
        turma: "2º ANO C",
        prev: 21,
        avaliados: 20,
        participacao: 95.2,
        n1Count: 3,
        n2Count: 2,
        n3Count: 2,
        n4Count: 3,
        inicianteCount: 6,
        fluenteCount: 4,
        n1Perc: 15.0,
        n2Perc: 10.0,
        n3Perc: 10.0,
        n4Perc: 15.0,
        iniciantePerc: 30.0,
        fluentePerc: 20.0,
        preTotalPerc: 50.0,
        leitoresPerc: 50.0,
        iflNum: 4.75,
        ifl: "4.75"
      }
    ]
  },
  {
    name: "E.M. ARTHUR DE ANDRADE",
    rawName: "E.M. ARTHUR DE ANDRADE",
    iflGeral: 6.30,
    iflGeralFormatted: "6.30",
    classes: [
      {
        id: "E.M. ARTHUR DE ANDRADE__2º ANO A",
        escola: "E.M. ARTHUR DE ANDRADE",
        turma: "2º ANO A",
        prev: 24,
        avaliados: 17,
        participacao: 70.8,
        n1Count: 0,
        n2Count: 0,
        n3Count: 2,
        n4Count: 1,
        inicianteCount: 6,
        fluenteCount: 8,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 11.8,
        n4Perc: 5.9,
        iniciantePerc: 35.3,
        fluentePerc: 47.1,
        preTotalPerc: 17.7,
        leitoresPerc: 82.4,
        iflNum: 7.35,
        ifl: "7.35"
      },
      {
        id: "E.M. ARTHUR DE ANDRADE__2º ANO B",
        escola: "E.M. ARTHUR DE ANDRADE",
        turma: "2º ANO B",
        prev: 22,
        avaliados: 16,
        participacao: 72.7,
        n1Count: 0,
        n2Count: 0,
        n3Count: 7,
        n4Count: 0,
        inicianteCount: 6,
        fluenteCount: 3,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 43.8,
        n4Perc: 0.0,
        iniciantePerc: 37.5,
        fluentePerc: 18.8,
        preTotalPerc: 43.8,
        leitoresPerc: 56.3,
        iflNum: 5.22,
        ifl: "5.22"
      },
      {
        id: "E.M. ARTHUR DE ANDRADE__2º ANO C",
        escola: "E.M. ARTHUR DE ANDRADE",
        turma: "2º ANO C",
        prev: 22,
        avaliados: 22,
        participacao: 100.0,
        n1Count: 0,
        n2Count: 1,
        n3Count: 7,
        n4Count: 1,
        inicianteCount: 4,
        fluenteCount: 9,
        n1Perc: 0.0,
        n2Perc: 4.5,
        n3Perc: 31.8,
        n4Perc: 4.5,
        iniciantePerc: 18.2,
        fluentePerc: 40.9,
        preTotalPerc: 40.8,
        leitoresPerc: 59.1,
        iflNum: 6.20,
        ifl: "6.20"
      },
      {
        id: "E.M. ARTHUR DE ANDRADE__2º ANO D",
        escola: "E.M. ARTHUR DE ANDRADE",
        turma: "2º ANO D",
        prev: 25,
        avaliados: 20,
        participacao: 80.0,
        n1Count: 0,
        n2Count: 1,
        n3Count: 4,
        n4Count: 3,
        inicianteCount: 6,
        fluenteCount: 6,
        n1Perc: 0.0,
        n2Perc: 5.0,
        n3Perc: 20.0,
        n4Perc: 15.0,
        iniciantePerc: 30.0,
        fluentePerc: 30.0,
        preTotalPerc: 40.0,
        leitoresPerc: 60.0,
        iflNum: 5.95,
        ifl: "5.95"
      }
    ]
  },
  {
    name: "E.M. ABDIAS JUNIOR SANTIAGO E SILVA",
    rawName: "E.M. ABDIAS JUNIOR SANTIAGO E SILVA",
    iflGeral: 5.22,
    iflGeralFormatted: "5.22",
    classes: [
      {
        id: "E.M. ABDIAS JUNIOR SANTIAGO E SILVA__2º ANO B",
        escola: "E.M. ABDIAS JUNIOR SANTIAGO E SILVA",
        turma: "2º ANO B",
        prev: 18,
        avaliados: 15,
        participacao: 83.3,
        n1Count: 0,
        n2Count: 0,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 8,
        fluenteCount: 2,
        n1Perc: 0.0,
        n2Perc: 0.0,
        n3Perc: 33.3,
        n4Perc: 0.0,
        iniciantePerc: 53.3,
        fluentePerc: 13.3,
        preTotalPerc: 33.3,
        leitoresPerc: 66.7,
        iflNum: 5.36,
        ifl: "5.36"
      },
      {
        id: "E.M. ABDIAS JUNIOR SANTIAGO E SILVA__2º ANO C",
        escola: "E.M. ABDIAS JUNIOR SANTIAGO E SILVA",
        turma: "2º ANO C",
        prev: 19,
        avaliados: 17,
        participacao: 89.5,
        n1Count: 0,
        n2Count: 2,
        n3Count: 5,
        n4Count: 0,
        inicianteCount: 7,
        fluenteCount: 3,
        n1Perc: 0.0,
        n2Perc: 11.8,
        n3Perc: 29.4,
        n4Perc: 0.0,
        iniciantePerc: 41.2,
        fluentePerc: 17.6,
        preTotalPerc: 41.2,
        leitoresPerc: 58.8,
        iflNum: 5.09,
        ifl: "5.09"
      }
    ]
  }
];

/**
 * 0 Escolas da Rede cujos dados do 1º Simulado NÃO foram incluídos neste envio.
 * Todas as escolas da rede estão 100% consolidadas!
 */
export const SIMULADO1_PENDING_SCHOOLS: string[] = [];
