export const RAW_CLASSES_ATIBAIA = [
  {
    "escola": "ANDRE FRANCO MONTORO E M",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 28,
    "avaliados": 26,
    "participacao": 93,
    "preTotal": 58,
    "n1": 12,
    "n2": 4,
    "n3": 0,
    "n4": 42,
    "iniciante": 35,
    "fluente": 8
  },
  {
    "escola": "ARMANDO TAMASSIA PADRE EM",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 27,
    "avaliados": 27,
    "participacao": 100,
    "preTotal": 49,
    "n1": 0,
    "n2": 26,
    "n3": 4,
    "n4": 19,
    "iniciante": 48,
    "fluente": 4
  },
  {
    "escola": "ARMANDO TAMASSIA PADRE EM",
    "turma": "2º ANO B MANHA ANUAL",
    "previstos": 27,
    "avaliados": 27,
    "participacao": 100,
    "preTotal": 40,
    "n1": 11,
    "n2": 15,
    "n3": 7,
    "n4": 7,
    "iniciante": 59,
    "fluente": 0
  },
  {
    "escola": "ARMANDO TAMASSIA PADRE EM",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 30,
    "avaliados": 29,
    "participacao": 97,
    "preTotal": 75,
    "n1": 3,
    "n2": 14,
    "n3": 10,
    "n4": 48,
    "iniciante": 21,
    "fluente": 3
  },
  {
    "escola": "CATARINA MARIA DOS REIS EMEFR",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 16,
    "avaliados": 15,
    "participacao": 94,
    "preTotal": 54,
    "n1": 20,
    "n2": 7,
    "n3": 0,
    "n4": 27,
    "iniciante": 33,
    "fluente": 13
  },
  {
    "escola": "CENTRO INTEGRADO DE EDUCACAO MUNICIPAL CIEM I PROFESSORA ELIZETE RODRIGUES",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 29,
    "avaliados": 29,
    "participacao": 100,
    "preTotal": 38,
    "n1": 7,
    "n2": 0,
    "n3": 10,
    "n4": 21,
    "iniciante": 59,
    "fluente": 3
  },
  {
    "escola": "CENTRO INTEGRADO DE EDUCACAO MUNICIPAL CIEM I PROFESSORA ELIZETE RODRIGUES",
    "turma": "2º ANO B MANHA ANUAL",
    "previstos": 27,
    "avaliados": 26,
    "participacao": 96,
    "preTotal": 39,
    "n1": 0,
    "n2": 8,
    "n3": 12,
    "n4": 19,
    "iniciante": 58,
    "fluente": 4
  },
  {
    "escola": "CENTRO INTEGRADO DE EDUCACAO MUNICIPAL CIEM I PROFESSORA ELIZETE RODRIGUES",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 26,
    "avaliados": 25,
    "participacao": 96,
    "preTotal": 36,
    "n1": 4,
    "n2": 0,
    "n3": 4,
    "n4": 28,
    "iniciante": 40,
    "fluente": 24
  },
  {
    "escola": "CENTRO INTEGRADO DE EDUCACAO MUNICIPAL CIEM I PROFESSORA ELIZETE RODRIGUES",
    "turma": "2º ANO D TARDE ANUAL",
    "previstos": 28,
    "avaliados": 26,
    "participacao": 93,
    "preTotal": 46,
    "n1": 0,
    "n2": 4,
    "n3": 0,
    "n4": 42,
    "iniciante": 46,
    "fluente": 8
  },
  {
    "escola": "CENTRO INTEGRADO DE EDUCACAO MUNICIPAL CIEM II PROFESSOR DOUTOR ORLANDO GIGLIOTTI",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 27,
    "avaliados": 26,
    "participacao": 96,
    "preTotal": 55,
    "n1": 12,
    "n2": 8,
    "n3": 0,
    "n4": 35,
    "iniciante": 38,
    "fluente": 8
  },
  {
    "escola": "CIEM 3 CENTRO INTEGRADO DE EDUCACAO MUNICIPAL PROFESSORA ESPERANCA APARECIDA GIACOMIN MAEDA",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 31,
    "avaliados": 30,
    "participacao": 97,
    "preTotal": 82,
    "n1": 23,
    "n2": 13,
    "n3": 3,
    "n4": 43,
    "iniciante": 17,
    "fluente": 0
  },
  {
    "escola": "CIEM 3 CENTRO INTEGRADO DE EDUCACAO MUNICIPAL PROFESSORA ESPERANCA APARECIDA GIACOMIN MAEDA",
    "turma": "2º ANO B INTEGRAL ANUAL",
    "previstos": 30,
    "avaliados": 27,
    "participacao": 90,
    "preTotal": 63,
    "n1": 4,
    "n2": 15,
    "n3": 11,
    "n4": 33,
    "iniciante": 33,
    "fluente": 4
  },
  {
    "escola": "EVA CORDULLA HAUER VALLEJO EMEIF",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 72,
    "n1": 11,
    "n2": 18,
    "n3": 0,
    "n4": 43,
    "iniciante": 25,
    "fluente": 4
  },
  {
    "escola": "EVA CORDULLA HAUER VALLEJO EMEIF",
    "turma": "2º ANO B INTEGRAL ANUAL",
    "previstos": 28,
    "avaliados": 27,
    "participacao": 96,
    "preTotal": 63,
    "n1": 7,
    "n2": 19,
    "n3": 4,
    "n4": 33,
    "iniciante": 37,
    "fluente": 0
  },
  {
    "escola": "FRANCISCO SILVEIRA BUENO PROF EM",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 25,
    "avaliados": 25,
    "participacao": 100,
    "preTotal": 40,
    "n1": 0,
    "n2": 12,
    "n3": 4,
    "n4": 24,
    "iniciante": 56,
    "fluente": 4
  },
  {
    "escola": "FRANCISCO SILVEIRA BUENO PROF EM",
    "turma": "2º ANO B MANHA ANUAL",
    "previstos": 27,
    "avaliados": 27,
    "participacao": 100,
    "preTotal": 48,
    "n1": 15,
    "n2": 7,
    "n3": 0,
    "n4": 26,
    "iniciante": 37,
    "fluente": 15
  },
  {
    "escola": "FRANCISCO SILVEIRA BUENO PROF EM",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 29,
    "avaliados": 29,
    "participacao": 100,
    "preTotal": 45,
    "n1": 0,
    "n2": 10,
    "n3": 14,
    "n4": 21,
    "iniciante": 48,
    "fluente": 7
  },
  {
    "escola": "FRANCISCO SILVEIRA BUENO PROF EM",
    "turma": "2º ANO D TARDE ANUAL",
    "previstos": 29,
    "avaliados": 29,
    "participacao": 100,
    "preTotal": 31,
    "n1": 0,
    "n2": 14,
    "n3": 3,
    "n4": 14,
    "iniciante": 45,
    "fluente": 24
  },
  {
    "escola": "GUILHERME PILEGGI CONTESINI PROF EM",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 30,
    "avaliados": 30,
    "participacao": 100,
    "preTotal": 41,
    "n1": 7,
    "n2": 0,
    "n3": 7,
    "n4": 27,
    "iniciante": 43,
    "fluente": 17
  },
  {
    "escola": "GUILHERME PILEGGI CONTESINI PROF EM",
    "turma": "2º ANO B TARDE ANUAL",
    "previstos": 29,
    "avaliados": 28,
    "participacao": 97,
    "preTotal": 55,
    "n1": 4,
    "n2": 4,
    "n3": 11,
    "n4": 36,
    "iniciante": 36,
    "fluente": 11
  },
  {
    "escola": "GUILHERME PILEGGI CONTESINI PROF EM",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 27,
    "avaliados": 26,
    "participacao": 96,
    "preTotal": 23,
    "n1": 4,
    "n2": 0,
    "n3": 0,
    "n4": 19,
    "iniciante": 62,
    "fluente": 15
  },
  {
    "escola": "IGNACIO BORGES EM",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 17,
    "avaliados": 17,
    "participacao": 100,
    "preTotal": 71,
    "n1": 18,
    "n2": 6,
    "n3": 0,
    "n4": 47,
    "iniciante": 29,
    "fluente": 0
  },
  {
    "escola": "JOSE APARECIDO FERREIRA FRANCO EM",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 47,
    "n1": 4,
    "n2": 0,
    "n3": 0,
    "n4": 43,
    "iniciante": 50,
    "fluente": 4
  },
  {
    "escola": "JOSE APARECIDO FERREIRA FRANCO EM",
    "turma": "2º ANO B MANHA ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 50,
    "n1": 11,
    "n2": 11,
    "n3": 7,
    "n4": 21,
    "iniciante": 32,
    "fluente": 18
  },
  {
    "escola": "JOSE APARECIDO FERREIRA FRANCO EM",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 28,
    "avaliados": 27,
    "participacao": 96,
    "preTotal": 37,
    "n1": 0,
    "n2": 7,
    "n3": 4,
    "n4": 26,
    "iniciante": 52,
    "fluente": 11
  },
  {
    "escola": "JOSE APARECIDO FERREIRA FRANCO EM",
    "turma": "2º ANO D TARDE ANUAL",
    "previstos": 25,
    "avaliados": 25,
    "participacao": 100,
    "preTotal": 36,
    "n1": 8,
    "n2": 4,
    "n3": 12,
    "n4": 12,
    "iniciante": 48,
    "fluente": 16
  },
  {
    "escola": "MARIA CECILIA DE LIMA EM",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 23,
    "avaliados": 22,
    "participacao": 96,
    "preTotal": 69,
    "n1": 5,
    "n2": 32,
    "n3": 0,
    "n4": 32,
    "iniciante": 27,
    "fluente": 5
  },
  {
    "escola": "MARIA HELENA FARIA FERRAZ PROFA EM",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 31,
    "avaliados": 31,
    "participacao": 100,
    "preTotal": 13,
    "n1": 0,
    "n2": 3,
    "n3": 0,
    "n4": 10,
    "iniciante": 71,
    "fluente": 16
  },
  {
    "escola": "MARIA HELENA FARIA FERRAZ PROFA EM",
    "turma": "2º ANO B TARDE ANUAL",
    "previstos": 31,
    "avaliados": 31,
    "participacao": 100,
    "preTotal": 9,
    "n1": 0,
    "n2": 0,
    "n3": 3,
    "n4": 6,
    "iniciante": 61,
    "fluente": 29
  },
  {
    "escola": "MARIA HELENA FARIA FERRAZ PROFA EM",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 29,
    "avaliados": 29,
    "participacao": 100,
    "preTotal": 37,
    "n1": 10,
    "n2": 3,
    "n3": 3,
    "n4": 21,
    "iniciante": 45,
    "fluente": 17
  },
  {
    "escola": "MARIA JOSE CINTRA DOS SANTOS PROFA EMEF",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 27,
    "avaliados": 27,
    "participacao": 100,
    "preTotal": 19,
    "n1": 0,
    "n2": 0,
    "n3": 4,
    "n4": 15,
    "iniciante": 63,
    "fluente": 19
  },
  {
    "escola": "MARIA JOSE CINTRA DOS SANTOS PROFA EMEF",
    "turma": "2º ANO B TARDE ANUAL",
    "previstos": 26,
    "avaliados": 26,
    "participacao": 100,
    "preTotal": 47,
    "n1": 4,
    "n2": 8,
    "n3": 8,
    "n4": 27,
    "iniciante": 31,
    "fluente": 23
  },
  {
    "escola": "MARIA JOSE CINTRA DOS SANTOS PROFA EMEF",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 26,
    "avaliados": 26,
    "participacao": 100,
    "preTotal": 54,
    "n1": 15,
    "n2": 4,
    "n3": 8,
    "n4": 27,
    "iniciante": 42,
    "fluente": 4
  },
  {
    "escola": "MARIA KAZUKO HIGASHIOKA EM",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 26,
    "avaliados": 26,
    "participacao": 100,
    "preTotal": 66,
    "n1": 4,
    "n2": 0,
    "n3": 12,
    "n4": 50,
    "iniciante": 31,
    "fluente": 4
  },
  {
    "escola": "MARIA KAZUKO HIGASHIOKA EM",
    "turma": "2º ANO B MANHA ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 51,
    "n1": 11,
    "n2": 7,
    "n3": 4,
    "n4": 29,
    "iniciante": 46,
    "fluente": 4
  },
  {
    "escola": "MARIA KAZUKO HIGASHIOKA EM",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 30,
    "n1": 4,
    "n2": 4,
    "n3": 4,
    "n4": 18,
    "iniciante": 57,
    "fluente": 14
  },
  {
    "escola": "MARIA KAZUKO HIGASHIOKA EM",
    "turma": "2º ANO D TARDE ANUAL",
    "previstos": 28,
    "avaliados": 26,
    "participacao": 93,
    "preTotal": 54,
    "n1": 4,
    "n2": 8,
    "n3": 4,
    "n4": 38,
    "iniciante": 35,
    "fluente": 12
  },
  {
    "escola": "NELSON JOSE PEDROSO ESTUDANTE EMEF",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 31,
    "avaliados": 31,
    "participacao": 100,
    "preTotal": 36,
    "n1": 10,
    "n2": 0,
    "n3": 3,
    "n4": 23,
    "iniciante": 55,
    "fluente": 10
  },
  {
    "escola": "NELSON JOSE PEDROSO ESTUDANTE EMEF",
    "turma": "2º ANO B TARDE ANUAL",
    "previstos": 21,
    "avaliados": 21,
    "participacao": 100,
    "preTotal": 68,
    "n1": 5,
    "n2": 29,
    "n3": 10,
    "n4": 24,
    "iniciante": 19,
    "fluente": 14
  },
  {
    "escola": "NELSON JOSE PEDROSO ESTUDANTE EMEF",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 25,
    "avaliados": 25,
    "participacao": 100,
    "preTotal": 36,
    "n1": 0,
    "n2": 4,
    "n3": 4,
    "n4": 28,
    "iniciante": 56,
    "fluente": 8
  },
  {
    "escola": "NIZE DE SOUZA B PACCINI EM",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 19,
    "avaliados": 19,
    "participacao": 100,
    "preTotal": 37,
    "n1": 5,
    "n2": 16,
    "n3": 0,
    "n4": 16,
    "iniciante": 58,
    "fluente": 5
  },
  {
    "escola": "PAULO FREIRE EDUCADOR ESCOLA MUNICIPAL",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 27,
    "avaliados": 26,
    "participacao": 96,
    "preTotal": 73,
    "n1": 4,
    "n2": 31,
    "n3": 15,
    "n4": 23,
    "iniciante": 19,
    "fluente": 8
  },
  {
    "escola": "PAULO FREIRE EDUCADOR ESCOLA MUNICIPAL",
    "turma": "2º ANO B INTEGRAL ANUAL",
    "previstos": 25,
    "avaliados": 25,
    "participacao": 100,
    "preTotal": 52,
    "n1": 4,
    "n2": 8,
    "n3": 4,
    "n4": 36,
    "iniciante": 36,
    "fluente": 12
  },
  {
    "escola": "PAULO FREIRE EDUCADOR ESCOLA MUNICIPAL",
    "turma": "2º ANO C INTEGRAL ANUAL",
    "previstos": 21,
    "avaliados": 21,
    "participacao": 100,
    "preTotal": 67,
    "n1": 14,
    "n2": 5,
    "n3": 10,
    "n4": 38,
    "iniciante": 33,
    "fluente": 0
  },
  {
    "escola": "PEDRO DE ALCANTARA DOS SANTOS SILVA EMEIEF",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 47,
    "n1": 0,
    "n2": 0,
    "n3": 11,
    "n4": 36,
    "iniciante": 46,
    "fluente": 7
  },
  {
    "escola": "RITA LOURDES CARDOSO DE ALMEIDA ALVIM PROFA EM",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 33,
    "avaliados": 32,
    "participacao": 97,
    "preTotal": 65,
    "n1": 6,
    "n2": 9,
    "n3": 3,
    "n4": 47,
    "iniciante": 31,
    "fluente": 3
  },
  {
    "escola": "ROSIRIS MARIA ANDREUCCI STOPA EM",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 27,
    "avaliados": 27,
    "participacao": 100,
    "preTotal": 41,
    "n1": 0,
    "n2": 0,
    "n3": 0,
    "n4": 41,
    "iniciante": 26,
    "fluente": 33
  },
  {
    "escola": "SERAFINA LUCA CHERFEN PROFA EM",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 34,
    "avaliados": 34,
    "participacao": 100,
    "preTotal": 32,
    "n1": 0,
    "n2": 0,
    "n3": 3,
    "n4": 29,
    "iniciante": 53,
    "fluente": 15
  },
  {
    "escola": "TAKAO ONO PREFEITO EMEIEF",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 62,
    "n1": 4,
    "n2": 4,
    "n3": 11,
    "n4": 43,
    "iniciante": 29,
    "fluente": 11
  },
  {
    "escola": "TAKAO ONO PREFEITO EMEIEF",
    "turma": "2º ANO B MANHA ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 37,
    "n1": 4,
    "n2": 0,
    "n3": 4,
    "n4": 29,
    "iniciante": 46,
    "fluente": 18
  },
  {
    "escola": "TAKAO ONO PREFEITO EMEIEF",
    "turma": "2º ANO C MANHA ANUAL",
    "previstos": 28,
    "avaliados": 28,
    "participacao": 100,
    "preTotal": 43,
    "n1": 18,
    "n2": 0,
    "n3": 0,
    "n4": 25,
    "iniciante": 54,
    "fluente": 4
  },
  {
    "escola": "TAKAO ONO PREFEITO EMEIEF",
    "turma": "2º ANO D TARDE ANUAL",
    "previstos": 29,
    "avaliados": 28,
    "participacao": 97,
    "preTotal": 86,
    "n1": 7,
    "n2": 25,
    "n3": 11,
    "n4": 43,
    "iniciante": 14,
    "fluente": 0
  },
  {
    "escola": "TAKAO ONO PREFEITO EMEIEF",
    "turma": "2º ANO E TARDE ANUAL",
    "previstos": 29,
    "avaliados": 29,
    "participacao": 100,
    "preTotal": 65,
    "n1": 7,
    "n2": 24,
    "n3": 3,
    "n4": 31,
    "iniciante": 34,
    "fluente": 0
  },
  {
    "escola": "THEREZINHA DO MENINO JESUS SILVEIRA CAMPOS SIRERA EMEF",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 31,
    "avaliados": 28,
    "participacao": 90,
    "preTotal": 36,
    "n1": 4,
    "n2": 7,
    "n3": 0,
    "n4": 25,
    "iniciante": 61,
    "fluente": 4
  },
  {
    "escola": "THEREZINHA DO MENINO JESUS SILVEIRA CAMPOS SIRERA EMEF",
    "turma": "2º ANO B TARDE ANUAL",
    "previstos": 27,
    "avaliados": 26,
    "participacao": 96,
    "preTotal": 54,
    "n1": 15,
    "n2": 15,
    "n3": 12,
    "n4": 12,
    "iniciante": 46,
    "fluente": 0
  },
  {
    "escola": "THEREZINHA DO MENINO JESUS SILVEIRA CAMPOS SIRERA EMEF",
    "turma": "2º ANO C TARDE ANUAL",
    "previstos": 30,
    "avaliados": 29,
    "participacao": 97,
    "preTotal": 37,
    "n1": 10,
    "n2": 14,
    "n3": 3,
    "n4": 10,
    "iniciante": 55,
    "fluente": 7
  },
  {
    "escola": "WALDA PAOLINETTI LOZASSO EM",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 26,
    "avaliados": 26,
    "participacao": 100,
    "preTotal": 69,
    "n1": 15,
    "n2": 0,
    "n3": 12,
    "n4": 42,
    "iniciante": 31,
    "fluente": 0
  },
  {
    "escola": "WALDEMAR BASTOS BUHLER EM",
    "turma": "2º ANO A MANHA ANUAL",
    "previstos": 30,
    "avaliados": 30,
    "participacao": 100,
    "preTotal": 60,
    "n1": 10,
    "n2": 7,
    "n3": 10,
    "n4": 33,
    "iniciante": 33,
    "fluente": 7
  },
  {
    "escola": "WALDEMAR BASTOS BUHLER EM",
    "turma": "2º ANO B MANHA ANUAL",
    "previstos": 29,
    "avaliados": 28,
    "participacao": 97,
    "preTotal": 47,
    "n1": 4,
    "n2": 18,
    "n3": 11,
    "n4": 14,
    "iniciante": 46,
    "fluente": 7
  },
  {
    "escola": "WALDEMAR BASTOS BUHLER EM",
    "turma": "2º ANO C MANHA ANUAL",
    "previstos": 31,
    "avaliados": 31,
    "participacao": 100,
    "preTotal": 52,
    "n1": 16,
    "n2": 23,
    "n3": 3,
    "n4": 10,
    "iniciante": 42,
    "fluente": 6
  },
  {
    "escola": "WALDEMAR BASTOS BUHLER EM",
    "turma": "2º ANO D TARDE ANUAL",
    "previstos": 31,
    "avaliados": 31,
    "participacao": 100,
    "preTotal": 67,
    "n1": 19,
    "n2": 29,
    "n3": 6,
    "n4": 13,
    "iniciante": 23,
    "fluente": 10
  },
  {
    "escola": "WALDEMAR BASTOS BUHLER EM",
    "turma": "2º ANO E TARDE ANUAL",
    "previstos": 32,
    "avaliados": 30,
    "participacao": 94,
    "preTotal": 73,
    "n1": 7,
    "n2": 23,
    "n3": 10,
    "n4": 33,
    "iniciante": 27,
    "fluente": 0
  },
  {
    "escola": "WALTER ENGRACIA DE OLIVEIRA PREFEITO EMEF",
    "turma": "2º ANO A INTEGRAL ANUAL",
    "previstos": 23,
    "avaliados": 23,
    "participacao": 100,
    "preTotal": 60,
    "n1": 4,
    "n2": 13,
    "n3": 17,
    "n4": 26,
    "iniciante": 30,
    "fluente": 9
  },
  {
    "escola": "WALTER ENGRACIA DE OLIVEIRA PREFEITO EMEF",
    "turma": "2º ANO B INTEGRAL ANUAL",
    "previstos": 25,
    "avaliados": 25,
    "participacao": 100,
    "preTotal": 44,
    "n1": 8,
    "n2": 4,
    "n3": 0,
    "n4": 32,
    "iniciante": 44,
    "fluente": 12
  },
  {
    "escola": "WALTER ENGRACIA DE OLIVEIRA PREFEITO EMEF",
    "turma": "2º ANO C INTEGRAL ANUAL",
    "previstos": 15,
    "avaliados": 15,
    "participacao": 100,
    "preTotal": 100,
    "n1": 20,
    "n2": 33,
    "n3": 0,
    "n4": 47,
    "iniciante": 0,
    "fluente": 0
  }
];
