export const RAW_CLASSES_PINDA = [
  {
    "escola": "EM PROFA MARIA MADUREIRA SALGADO DONA MINICA",
    "turma": "Geral",
    "previstos": 12,
    "avaliados": 12,
    "participacao": 100,
    "preTotal": 42,
    "n1": 0,
    "n2": 0,
    "n3": 17,
    "n4": 25,
    "iniciante": 50,
    "fluente": 8
  },
  {
    "escola": "ESCOLA MUN PADRE MARIO ANTONIO BONOTTI REDENTORISTA",
    "turma": "Geral",
    "previstos": 46,
    "avaliados": 46,
    "participacao": 100,
    "preTotal": 48,
    "n1": 9,
    "n2": 4,
    "n3": 15,
    "n4": 20,
    "iniciante": 37,
    "fluente": 15
  },
  {
    "escola": "ESCOLA MUNICIPAL ABDIAS JUNIOR SANTIAGO E SILVA",
    "turma": "Geral",
    "previstos": 47,
    "avaliados": 47,
    "participacao": 100,
    "preTotal": 51,
    "n1": 2,
    "n2": 4,
    "n3": 15,
    "n4": 30,
    "iniciante": 43,
    "fluente": 6
  },
  {
    "escola": "ESCOLA MUNICIPAL ARTHUR DE ANDRADE",
    "turma": "Geral",
    "previstos": 78,
    "avaliados": 76,
    "participacao": 97,
    "preTotal": 54,
    "n1": 5,
    "n2": 4,
    "n3": 12,
    "n4": 33,
    "iniciante": 32,
    "fluente": 14
  },
  {
    "escola": "ESCOLA MUNICIPAL DOUTOR ANGELO PAZ DA SILVA",
    "turma": "Geral",
    "previstos": 48,
    "avaliados": 46,
    "participacao": 96,
    "preTotal": 33,
    "n1": 2,
    "n2": 2,
    "n3": 11,
    "n4": 17,
    "iniciante": 52,
    "fluente": 15
  },
  {
    "escola": "ESCOLA MUNICIPAL DR ANDRE FRANCO MONTORO",
    "turma": "Geral",
    "previstos": 57,
    "avaliados": 55,
    "participacao": 96,
    "preTotal": 40,
    "n1": 7,
    "n2": 4,
    "n3": 4,
    "n4": 25,
    "iniciante": 51,
    "fluente": 9
  },
  {
    "escola": "ESCOLA MUNICIPAL DR FRANCISCO DE ASSIS CESAR",
    "turma": "Geral",
    "previstos": 49,
    "avaliados": 48,
    "participacao": 98,
    "preTotal": 44,
    "n1": 2,
    "n2": 0,
    "n3": 2,
    "n4": 40,
    "iniciante": 44,
    "fluente": 13
  },
  {
    "escola": "ESCOLA MUNICIPAL DULCE PEDROSA ROMEIRO GUIMARAES",
    "turma": "Geral",
    "previstos": 37,
    "avaliados": 36,
    "participacao": 97,
    "preTotal": 61,
    "n1": 3,
    "n2": 0,
    "n3": 0,
    "n4": 58,
    "iniciante": 33,
    "fluente": 6
  },
  {
    "escola": "ESCOLA MUNICIPAL JOAO CESARIO",
    "turma": "Geral",
    "previstos": 100,
    "avaliados": 98,
    "participacao": 98,
    "preTotal": 51,
    "n1": 8,
    "n2": 1,
    "n3": 7,
    "n4": 35,
    "iniciante": 38,
    "fluente": 11
  },
  {
    "escola": "ESCOLA MUNICIPAL JOAO KOLENDA LEMOS",
    "turma": "Geral",
    "previstos": 92,
    "avaliados": 90,
    "participacao": 98,
    "preTotal": 61,
    "n1": 10,
    "n2": 21,
    "n3": 4,
    "n4": 26,
    "iniciante": 36,
    "fluente": 3
  },
  {
    "escola": "ESCOLA MUNICIPAL JOSE GONCALVES DA SILVA SEU JUQUINHA",
    "turma": "Geral",
    "previstos": 66,
    "avaliados": 64,
    "participacao": 97,
    "preTotal": 63,
    "n1": 9,
    "n2": 14,
    "n3": 5,
    "n4": 34,
    "iniciante": 27,
    "fluente": 11
  },
  {
    "escola": "ESCOLA MUNICIPAL PADRE ZEZINHO",
    "turma": "Geral",
    "previstos": 45,
    "avaliados": 45,
    "participacao": 100,
    "preTotal": 31,
    "n1": 0,
    "n2": 0,
    "n3": 2,
    "n4": 29,
    "iniciante": 51,
    "fluente": 18
  },
  {
    "escola": "ESCOLA MUNICIPAL PROF LAURO VICENTE DE AZEVEDO",
    "turma": "Geral",
    "previstos": 45,
    "avaliados": 45,
    "participacao": 100,
    "preTotal": 67,
    "n1": 9,
    "n2": 7,
    "n3": 7,
    "n4": 44,
    "iniciante": 22,
    "fluente": 11
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFA MADALENA CALTABIANO SALUM BENJAMIM",
    "turma": "Geral",
    "previstos": 17,
    "avaliados": 16,
    "participacao": 94,
    "preTotal": 88,
    "n1": 25,
    "n2": 0,
    "n3": 0,
    "n4": 63,
    "iniciante": 13,
    "fluente": 0
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFA MARIA APARECIDA ARANTES VASQUES",
    "turma": "Geral",
    "previstos": 46,
    "avaliados": 41,
    "participacao": 89,
    "preTotal": 46,
    "n1": 2,
    "n2": 0,
    "n3": 12,
    "n4": 32,
    "iniciante": 34,
    "fluente": 20
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFA MARIA APARECIDA CAMARGO DE SOUZA",
    "turma": "Geral",
    "previstos": 7,
    "avaliados": 7,
    "participacao": 100,
    "preTotal": 57,
    "n1": 0,
    "n2": 0,
    "n3": 29,
    "n4": 29,
    "iniciante": 29,
    "fluente": 14
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFA MARIA HELENA RIBEIRO VILELA",
    "turma": "Geral",
    "previstos": 50,
    "avaliados": 49,
    "participacao": 98,
    "preTotal": 51,
    "n1": 6,
    "n2": 4,
    "n3": 6,
    "n4": 35,
    "iniciante": 41,
    "fluente": 8
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFA MARIA ZARA MINE RENOLDI DOS SANTOS",
    "turma": "Geral",
    "previstos": 42,
    "avaliados": 42,
    "participacao": 100,
    "preTotal": 38,
    "n1": 0,
    "n2": 5,
    "n3": 0,
    "n4": 33,
    "iniciante": 50,
    "fluente": 12
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFA ODETE CORREA MADUREIRA",
    "turma": "Geral",
    "previstos": 51,
    "avaliados": 47,
    "participacao": 92,
    "preTotal": 64,
    "n1": 2,
    "n2": 11,
    "n3": 13,
    "n4": 38,
    "iniciante": 26,
    "fluente": 11
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFA RACHEL DE AGUIAR LOBERTO",
    "turma": "Geral",
    "previstos": 50,
    "avaliados": 48,
    "participacao": 96,
    "preTotal": 38,
    "n1": 6,
    "n2": 0,
    "n3": 10,
    "n4": 21,
    "iniciante": 52,
    "fluente": 10
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFA REGINA CELIA MADUREIRA DE SOUZA LIMA",
    "turma": "Geral",
    "previstos": 62,
    "avaliados": 60,
    "participacao": 97,
    "preTotal": 55,
    "n1": 3,
    "n2": 2,
    "n3": 15,
    "n4": 35,
    "iniciante": 38,
    "fluente": 7
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR ALEXANDRE MACHADO SALGADO",
    "turma": "Geral",
    "previstos": 80,
    "avaliados": 79,
    "participacao": 99,
    "preTotal": 58,
    "n1": 8,
    "n2": 11,
    "n3": 10,
    "n4": 29,
    "iniciante": 29,
    "fluente": 13
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR AUGUSTO CESAR RIBEIRO",
    "turma": "Geral",
    "previstos": 37,
    "avaliados": 36,
    "participacao": 97,
    "preTotal": 47,
    "n1": 3,
    "n2": 0,
    "n3": 17,
    "n4": 28,
    "iniciante": 39,
    "fluente": 14
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR ELIAS BARGIS MATHIAS",
    "turma": "Geral",
    "previstos": 92,
    "avaliados": 90,
    "participacao": 98,
    "preTotal": 46,
    "n1": 3,
    "n2": 14,
    "n3": 8,
    "n4": 20,
    "iniciante": 47,
    "fluente": 8
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR FELIX ADIB MIGUEL",
    "turma": "Geral",
    "previstos": 43,
    "avaliados": 43,
    "participacao": 100,
    "preTotal": 51,
    "n1": 9,
    "n2": 5,
    "n3": 7,
    "n4": 30,
    "iniciante": 30,
    "fluente": 19
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR JOAQUIM PEREIRA DA SILVA",
    "turma": "Geral",
    "previstos": 123,
    "avaliados": 122,
    "participacao": 99,
    "preTotal": 42,
    "n1": 3,
    "n2": 8,
    "n3": 5,
    "n4": 25,
    "iniciante": 31,
    "fluente": 27
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR MARIO DE ASSIS CESAR",
    "turma": "Geral",
    "previstos": 37,
    "avaliados": 37,
    "participacao": 100,
    "preTotal": 54,
    "n1": 11,
    "n2": 16,
    "n3": 0,
    "n4": 27,
    "iniciante": 38,
    "fluente": 8
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR MOACYR DE ALMEIDA",
    "turma": "Geral",
    "previstos": 16,
    "avaliados": 15,
    "participacao": 94,
    "preTotal": 40,
    "n1": 7,
    "n2": 0,
    "n3": 0,
    "n4": 33,
    "iniciante": 47,
    "fluente": 13
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR ORLANDO PIRES",
    "turma": "Geral",
    "previstos": 31,
    "avaliados": 23,
    "participacao": 74,
    "preTotal": 35,
    "n1": 4,
    "n2": 0,
    "n3": 4,
    "n4": 26,
    "iniciante": 57,
    "fluente": 9
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSOR PAULO FREIRE",
    "turma": "Geral",
    "previstos": 27,
    "avaliados": 27,
    "participacao": 100,
    "preTotal": 7,
    "n1": 0,
    "n2": 4,
    "n3": 0,
    "n4": 4,
    "iniciante": 44,
    "fluente": 48
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSORA GILDA PIORINI MOLICA",
    "turma": "Geral",
    "previstos": 51,
    "avaliados": 49,
    "participacao": 96,
    "preTotal": 39,
    "n1": 4,
    "n2": 4,
    "n3": 12,
    "n4": 18,
    "iniciante": 47,
    "fluente": 14
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSORA ISABEL DO CARMO NOGUEIRA",
    "turma": "Geral",
    "previstos": 81,
    "avaliados": 81,
    "participacao": 100,
    "preTotal": 35,
    "n1": 0,
    "n2": 6,
    "n3": 6,
    "n4": 22,
    "iniciante": 51,
    "fluente": 15
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSORA JULIETA REALE VIEIRA",
    "turma": "Geral",
    "previstos": 52,
    "avaliados": 50,
    "participacao": 96,
    "preTotal": 64,
    "n1": 4,
    "n2": 26,
    "n3": 8,
    "n4": 26,
    "iniciante": 34,
    "fluente": 2
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSORA RUTH AZEVEDO ROMEIRO",
    "turma": "Geral",
    "previstos": 41,
    "avaliados": 41,
    "participacao": 100,
    "preTotal": 59,
    "n1": 10,
    "n2": 27,
    "n3": 2,
    "n4": 20,
    "iniciante": 39,
    "fluente": 2
  },
  {
    "escola": "ESCOLA MUNICIPAL PROFESSORA YVONE APPARECIDA ARANTES CORREA",
    "turma": "Geral",
    "previstos": 20,
    "avaliados": 19,
    "participacao": 95,
    "preTotal": 84,
    "n1": 0,
    "n2": 21,
    "n3": 5,
    "n4": 58,
    "iniciante": 11,
    "fluente": 5
  },
  {
    "escola": "ESCOLA MUNICIPAL SERAFIM FERREIRA SR SARA",
    "turma": "Geral",
    "previstos": 60,
    "avaliados": 60,
    "participacao": 100,
    "preTotal": 35,
    "n1": 5,
    "n2": 12,
    "n3": 5,
    "n4": 13,
    "iniciante": 52,
    "fluente": 13
  },
  {
    "escola": "ESCOLA MUNICIPAL VITO ARDITO",
    "turma": "Geral",
    "previstos": 36,
    "avaliados": 36,
    "participacao": 100,
    "preTotal": 42,
    "n1": 6,
    "n2": 11,
    "n3": 3,
    "n4": 22,
    "iniciante": 50,
    "fluente": 8
  }
];
